/**
 * Golden tests: fixture → parseAndCheck → generateResources → stable TypeScript source.
 * Covers branded scalars, ARI factories, payload types, and ContentRegistry.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { pageDetailProgram } from "../../../fixtures";
import { parseAndCheck } from "../../parse-and-check";
import { generateResources } from "./generate-resources";

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), "../../../fixtures");

function loadFixture(name: string): string {
  return readFileSync(join(fixturesDir, name), "utf8");
}

function normalizeWhitespace(code: string): string {
  return code.trim().replace(/\n{3,}/g, "\n\n");
}

/** Collect module specifiers from top-level `import … from "…"` / `'…'`. */
function importSpecifiers(code: string): string[] {
  const specs: string[] = [];
  const re = /^\s*import\s+[\s\S]*?\s+from\s+["']([^"']+)["']/gm;
  for (const match of code.matchAll(re)) {
    specs.push(match[1]!);
  }
  return specs;
}

function expectOnlyZielRuntimeImport(code: string): void {
  const specs = importSpecifiers(code);
  expect(specs).toEqual(["@xndrjs/ziel"]);
  expect(code).toContain('import { ari, s } from "@xndrjs/ziel";');
  expect(code).not.toMatch(/from\s+["']@xndrjs\/ziel\/compile["']/);
}

const POST_DETAIL_GOLDEN = `
/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */

import { ari, s } from "@xndrjs/ziel";

declare const __brand: unique symbol;
type Branded<Name extends string, T> = T & { readonly [__brand]: Name };

export type PostId = Branded<"PostId", string>;

export type UserId = Branded<"UserId", string>;

export type Locale = Branded<"Locale", string>;

export const Scalars = {
  PostId: (value: string): PostId => value as PostId,
  UserId: (value: string): UserId => value as UserId,
  Locale: (value: string): Locale => value as Locale,
} as const;

export const postAri = ari(
  "Post",
  s.object({ id: s.string(), locale: s.string() }),
);
export type PostResource = ReturnType<typeof postAri>;

export const userAri = ari(
  "User",
  s.object({ id: s.string() }),
);
export type UserResource = ReturnType<typeof userAri>;

export type PostPayload = {
  id: PostId;
  title: string;
  content: string;
  authorId: UserId;
};

export type UserPayload = {
  id: UserId;
  username: string;
};

export type ContentRegistry = {
  Post: PostPayload;
  User: UserPayload;
};
`;

const PAGE_DETAIL_GOLDEN = `
/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */

import { ari, s } from "@xndrjs/ziel";

declare const __brand: unique symbol;
type Branded<Name extends string, T> = T & { readonly [__brand]: Name };

export type Locale = Branded<"Locale", string>;

export type SpaceId = Branded<"SpaceId", string>;

export type EnvironmentId = Branded<"EnvironmentId", string>;

export type EntryId = Branded<"EntryId", string>;

export type AssetId = Branded<"AssetId", string>;

export type CustomReferenceValue = Branded<"CustomReferenceValue", string>;

export type Sku = Branded<"Sku", string>;

export const Scalars = {
  Locale: (value: string): Locale => value as Locale,
  SpaceId: (value: string): SpaceId => value as SpaceId,
  EnvironmentId: (value: string): EnvironmentId => value as EnvironmentId,
  EntryId: (value: string): EntryId => value as EntryId,
  AssetId: (value: string): AssetId => value as AssetId,
  CustomReferenceValue: (value: string): CustomReferenceValue => value as CustomReferenceValue,
  Sku: (value: string): Sku => value as Sku,
} as const;

export const entryAri = ari(
  "Entry",
  s.object({ spaceId: s.string(), environmentId: s.string(), id: s.string(), locale: s.string() }),
);
export type EntryResource = ReturnType<typeof entryAri>;

export const assetAri = ari(
  "Asset",
  s.object({ spaceId: s.string(), environmentId: s.string(), id: s.string(), locale: s.string() }),
);
export type AssetResource = ReturnType<typeof assetAri>;

export const customReferenceAri = ari(
  "CustomReference",
  s.object({ ref: s.string(), locale: s.string() }),
);
export type CustomReferenceResource = ReturnType<typeof customReferenceAri>;

export const pageAri = ari(
  "Page",
  s.object({ spaceId: s.string(), environmentId: s.string(), id: s.string(), locale: s.string() }),
);
export type PageResource = ReturnType<typeof pageAri>;

export type EntryPayload = {
  type: "Hero";
  id: EntryId;
  title: string;
  imageId: AssetId;
} | {
  type: "Tabs";
  id: EntryId;
  title: string;
  tabs: {
    id: EntryId;
  }[];
} | {
  type: "Tab";
  id: EntryId;
  title: string;
  strips: {
    id: EntryId;
  }[];
} | {
  type: "Product";
  id: EntryId;
  sku: Sku;
  title: string;
} | {
  type: "Menu";
  id: EntryId;
  title: string;
  logoId: AssetId;
} | {
  type: "Footer";
  id: EntryId;
  title: string;
  logoId: AssetId;
} | {
  type: "Page";
  id: EntryId;
  title: string;
} | {
  type: "SiteInternalLink";
  id: EntryId;
  targetId: EntryId;
};

export type AssetPayload = {
  type: "Asset";
  id: AssetId;
  url: string;
  title: string;
  kind: "image" | "video" | "document";
};

export type CustomReferencePayload = {
  type: "Entry";
  spaceId: SpaceId;
  environmentId: EnvironmentId;
  id: EntryId;
} | {
  type: "Asset";
  spaceId: SpaceId;
  environmentId: EnvironmentId;
  id: AssetId;
};

export type PagePayload = {
  id: EntryId;
  title: string;
  menuId: EntryId;
  footerId: EntryId;
  strips: {
    id: EntryId;
  }[];
  related: CustomReferenceValue[];
};

export type ContentRegistry = {
  Entry: EntryPayload;
  Asset: AssetPayload;
  CustomReference: CustomReferencePayload;
  Page: PagePayload;
};
`;

describe("generateResources golden", () => {
  it("post-detail.ziel → stable source (scalars, ARIs, payloads, registry)", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("post-detail.ziel"),
      "file:///fixtures/post-detail.ziel"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateResources(program);
    expectOnlyZielRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(POST_DETAIL_GOLDEN));
  });

  it("page-detail.ziel → stable source (unions, resourceRef, typeProjection)", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("page-detail.ziel"),
      "file:///fixtures/page-detail.ziel"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateResources(program);
    expectOnlyZielRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(PAGE_DETAIL_GOLDEN));

    // Spot-check cases the golden must cover.
    expect(code).toContain("export type EntryPayload = {");
    expect(code).toContain(`type: "Hero"`);
    expect(code).toContain(`type: "SiteInternalLink"`);
    expect(code).toContain(
      `export type CustomReferencePayload = {
  type: "Entry";
  spaceId: SpaceId;
  environmentId: EnvironmentId;
  id: EntryId;
} | {
  type: "Asset";
  spaceId: SpaceId;
  environmentId: EnvironmentId;
  id: AssetId;
};`
    );
    expect(code).toContain("tabs: {\n    id: EntryId;\n  }[];");
    expect(code).toContain("export const entryAri = ari(");
    expect(code).toContain("export const customReferenceAri = ari(");
    expect(code).not.toContain("EditorialModulePayload");
    expect(code).not.toContain("editorialModuleAri");
    expect(code).not.toContain("TabCollection");
    expect(code).not.toContain("heroAri");
    expect(code).toContain(`type: "Tabs"`);
    expect(code).toContain(`type: "Product"`);
    expect(code).toContain("strips: {\n    id: EntryId;\n  }[];");
    expect(code).not.toContain("EditorialModule.type");
    expect(code).not.toContain("typeProjection");
  });

  it("pageDetailProgram() IR path matches page-detail fixture emit (span-free)", () => {
    const fromFixture = parseAndCheck(
      loadFixture("page-detail.ziel"),
      "file:///fixtures/page-detail.ziel"
    );
    expect(fromFixture.diagnostics).toEqual([]);

    const fixtureCode = generateResources(fromFixture.program).code;
    const irCode = generateResources(pageDetailProgram()).code;

    expect(normalizeWhitespace(irCode)).toBe(normalizeWhitespace(fixtureCode));
    expect(normalizeWhitespace(irCode)).toBe(normalizeWhitespace(PAGE_DETAIL_GOLDEN));
    expectOnlyZielRuntimeImport(irCode);
  });
});
