/**
 * Datasource codegen entry: checked `Program` → TypeScript source string.
 * Emits context types, `createDataSources`, and `defineDataSourceFor` wiring.
 * Generated code imports runtime only from `@xndrjs/ziel`.
 */
import type { Program } from "../../../ir";
import { datasourcesNeedSourceRouteContext, emitDataSources } from "../datasources";

const GENERATED_HEADER = "/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */";

const DEFAULT_IMPORT_FROM = "@xndrjs/ziel";
const DEFAULT_REGISTRY_TYPE_NAME = "ContentRegistry";

export type GenerateDataSourcesOptions = {
  /** Module specifier for runtime imports. Default: `@xndrjs/ziel`. */
  importFrom?: string;
  /** Name of the registry type used as the `DataSource` generic. Default: `ContentRegistry`. */
  registryTypeName?: string;
};

export type GenerateDataSourcesResult = {
  /** Full TypeScript module source. */
  code: string;
};

type ResolvedOptions = {
  importFrom: string;
  registryTypeName: string;
};

function resolveOptions(options?: GenerateDataSourcesOptions): ResolvedOptions {
  return {
    importFrom: options?.importFrom ?? DEFAULT_IMPORT_FROM,
    registryTypeName: options?.registryTypeName ?? DEFAULT_REGISTRY_TYPE_NAME,
  };
}

function emitRuntimeImport(importFrom: string, program: Program): string {
  const symbols = ["defineDataSourceFor", "type DataSource", "type ResourceLoadContext"];
  if (datasourcesNeedSourceRouteContext(program)) {
    symbols.push("type SourceRouteContext");
  }
  return `import { ${symbols.join(", ")} } from ${JSON.stringify(importFrom)};`;
}

/**
 * Generate TypeScript source for datasource factories in `program`.
 *
 * Input should already be checked (`checkProgram` / `parseAndCheck`).
 * Output is a pure string (no filesystem writes). Empty when no datasources.
 */
export function generateDataSources(
  program: Program,
  options?: GenerateDataSourcesOptions
): GenerateDataSourcesResult {
  const { importFrom, registryTypeName } = resolveOptions(options);
  const body = emitDataSources(program, registryTypeName);

  const parts: string[] = [GENERATED_HEADER];

  if (body.length > 0) {
    parts.push(emitRuntimeImport(importFrom, program));
    parts.push(body);
  }

  return { code: `${parts.join("\n\n")}\n` };
}
