/**
 * Golden tests: fixture → parseAndCheck → generateProjections → stable TypeScript source.
 * Covers query-scoped aggregates, alias restoration, and memoized `project*`.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { parseAndCheck } from "../../parse-and-check";
import { generateProjections } from "./generate-projections";

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), "../../../fixtures");

function loadFixture(name: string): string {
  return readFileSync(join(fixturesDir, name), "utf8");
}

function normalizeWhitespace(code: string): string {
  return code.trim().replace(/\n{3,}/g, "\n\n");
}

/** Collect module specifiers from top-level `import … from "…"` / `'…'`. */
function importSpecifiers(code: string): string[] {
  const specs: string[] = [];
  const re = /^\s*import\s+[\s\S]*?\s+from\s+["']([^"']+)["']/gm;
  for (const match of code.matchAll(re)) {
    specs.push(match[1]!);
  }
  return specs;
}

function expectOnlyZielRuntimeImport(code: string): void {
  const specs = importSpecifiers(code);
  expect(specs).toEqual(["@xndrjs/ziel"]);
  expect(code).toMatch(
    /import \{ type ContentMap(?:, type ApplicationResourceIdentifier, type ResourceKey)? \} from "@xndrjs\/ziel";/
  );
  expect(code).not.toMatch(/from\s+["']@xndrjs\/ziel\/compile["']/);
}

const POST_DETAIL_PROJECTION_GOLDEN = `/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */

import { type ContentMap } from "@xndrjs/ziel";

export type PostDetail_Post = {
  id: PostId;
  title: string;
  content: string;
  author: PostDetail_User;
};

export type PostDetail_User = {
  id: UserId;
  username: string;
};

export type PostDetailResult = PostDetail_Post;

export function projectPostDetail(
  root: ReturnType<typeof postAri>,
  contentMap: ContentMap<ContentRegistry>,
  args: {
    params: PostDetailParams;
    executionContext: PostDetailExecutionContext;
  },
): PostDetailResult {
  const memo = new Map<string, unknown>();

  const projectOnPost = (resource: any, payload: any): any => {
    const shell: any = {};
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.title = payload.title;
    shell.content = payload.content;
    shell.author = projectNode(userAri({ id: payload.authorId }));
    return shell;
  };

  const projectOnUser = (resource: any, payload: any): any => {
    const shell: any = {};
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.username = payload.username;
    return shell;
  };

  const projectNode = (ari: any): unknown => {
    const key = ari.toString();
    if (memo.has(key)) return memo.get(key);
    const payload = contentMap.get(ari as never);
    if (payload === undefined) return undefined;
    switch (ari.type) {
      case "Post":
        return projectOnPost(ari, payload);
      case "User":
        return projectOnUser(ari, payload);
      default:
        throw new Error(
          "projectPostDetail: unexpected resource type " + JSON.stringify(ari.type)
        );
    }
  };

  return projectNode(root) as PostDetailResult;
}
`;

const PAGE_DETAIL_PROJECTION_GOLDEN = `/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */

import { type ContentMap, type ApplicationResourceIdentifier, type ResourceKey } from "@xndrjs/ziel";

export type PageDetail_Page = {
  id: EntryId;
  title: string;
  menu: PageDetail_Entry_Menu;
  footer: PageDetail_Entry_Footer;
  strips: PageDetail_Entry[];
  related: (PageDetail_Entry | PageDetail_Asset)[];
};

export type PageDetail_Entry_Hero = {
  type: "Hero";
  id: EntryId;
  title: string;
  imageId: AssetId;
  image: PageDetail_Asset;
};

export type PageDetail_Entry_Tabs = {
  type: "Tabs";
  id: EntryId;
  title: string;
  tabs: PageDetail_Entry[];
};

export type PageDetail_Entry_Tab = {
  type: "Tab";
  id: EntryId;
  title: string;
  strips: PageDetail_Entry[];
};

export type PageDetail_Entry_Menu = {
  type: "Menu";
  id: EntryId;
  title: string;
  logoId: AssetId;
  logo: PageDetail_Asset;
};

export type PageDetail_Entry_Footer = {
  type: "Footer";
  id: EntryId;
  title: string;
  logoId: AssetId;
  logo: PageDetail_Asset;
};

export type PageDetail_Entry_SiteInternalLink = {
  type: "SiteInternalLink";
  id: EntryId;
  targetId: EntryId;
  target: PageDetail_Entry;
};

export type PageDetail_Entry_Default = {};

export type PageDetail_Entry = PageDetail_Entry_Hero | PageDetail_Entry_Tabs | PageDetail_Entry_Tab | PageDetail_Entry_Menu | PageDetail_Entry_Footer | PageDetail_Entry_SiteInternalLink | PageDetail_Entry_Default;

export type PageDetail_Asset = {
  type: "Asset";
  id: AssetId;
  url: string;
  title: string;
  kind: "image" | "video" | "document";
};

export type PageDetailResult = PageDetail_Page;

export function projectPageDetail(
  root: ReturnType<typeof pageAri>,
  contentMap: ContentMap<ContentRegistry>,
  args: {
    params: PageDetailParams;
    executionContext: PageDetailExecutionContext;
    redirects: ReadonlyMap<ResourceKey, ApplicationResourceIdentifier>;
  },
): PageDetailResult {
  const memo = new Map<string, unknown>();

  const projectOnPage = (resource: any, payload: any): any => {
    const shell: any = {};
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.title = payload.title;
    shell.menu = projectNode(entryAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: payload.menuId, locale: resource.key[0].locale }));
    shell.footer = projectNode(entryAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: payload.footerId, locale: resource.key[0].locale }));
    shell.strips = payload.strips.map((pageLink: any) => projectNode(entryAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: pageLink.id, locale: resource.key[0].locale })));
    shell.related = payload.related.map((ref: any) => projectNode(customReferenceAri({ ref: ref, locale: resource.key[0].locale })));
    return shell;
  };

  const projectOnEntry = (resource: any, payload: any): any => {
    if (payload.type == "Hero") {
      const shell: any = {};
      memo.set(resource.toString(), shell);
      shell.type = payload.type;
      shell.id = payload.id;
      shell.title = payload.title;
      shell.imageId = payload.imageId;
      shell.image = projectNode(assetAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: payload.imageId, locale: resource.key[0].locale }));
      return shell;
    } else if (payload.type == "Tabs") {
      const shell: any = {};
      memo.set(resource.toString(), shell);
      shell.type = payload.type;
      shell.id = payload.id;
      shell.title = payload.title;
      shell.tabs = payload.tabs.map((tabLink: any) => projectNode(entryAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: tabLink.id, locale: resource.key[0].locale })));
      return shell;
    } else if (payload.type == "Tab") {
      const shell: any = {};
      memo.set(resource.toString(), shell);
      shell.type = payload.type;
      shell.id = payload.id;
      shell.title = payload.title;
      shell.strips = payload.strips.map((entryLink: any) => projectNode(entryAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: entryLink.id, locale: resource.key[0].locale })));
      return shell;
    } else if (payload.type == "Menu") {
      const shell: any = {};
      memo.set(resource.toString(), shell);
      shell.type = payload.type;
      shell.id = payload.id;
      shell.title = payload.title;
      shell.logoId = payload.logoId;
      shell.logo = projectNode(assetAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: payload.logoId, locale: resource.key[0].locale }));
      return shell;
    } else if (payload.type == "Footer") {
      const shell: any = {};
      memo.set(resource.toString(), shell);
      shell.type = payload.type;
      shell.id = payload.id;
      shell.title = payload.title;
      shell.logoId = payload.logoId;
      shell.logo = projectNode(assetAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: payload.logoId, locale: resource.key[0].locale }));
      return shell;
    } else if (payload.type == "SiteInternalLink") {
      const shell: any = {};
      memo.set(resource.toString(), shell);
      shell.type = payload.type;
      shell.id = payload.id;
      shell.targetId = payload.targetId;
      shell.target = projectNode(entryAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: payload.targetId, locale: resource.key[0].locale }));
      return shell;
    } else {
      const shell: any = {};
      memo.set(resource.toString(), shell);
      return shell;
    }
  };

  const projectOnAsset = (resource: any, payload: any): any => {
    const shell: any = {};
    memo.set(resource.toString(), shell);
    shell.type = payload.type;
    shell.id = payload.id;
    shell.url = payload.url;
    shell.title = payload.title;
    shell.kind = payload.kind;
    return shell;
  };

  const projectNode = (ari: any): unknown => {
    const key = ari.toString();
    if (memo.has(key)) return memo.get(key);
    const payload = contentMap.get(ari as never);
    if (payload === undefined) return undefined;
    switch (ari.type) {
      case "Page":
        return projectOnPage(ari, payload);
      case "Entry":
        return projectOnEntry(ari, payload);
      case "Asset":
        return projectOnAsset(ari, payload);
      case "CustomReference": {
        const canonical = args.redirects.get(ari.toString());
        if (canonical === undefined) return undefined;
        return projectNode(canonical);
      }
      default:
        throw new Error(
          "projectPageDetail: unexpected resource type " + JSON.stringify(ari.type)
        );
    }
  };

  return projectNode(root) as PageDetailResult;
}
`;
const HOMEPAGE_MULTI_PROJECTION_GOLDEN = `/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */

import { type ContentMap } from "@xndrjs/ziel";

export type Homepage_Page = {
  id: PageId;
  title: string;
};

export type Homepage_UserSession = {
  id: SessionId;
  userId: string;
};

export type HomepageResult = {
  page: Homepage_Page;
  session: Homepage_UserSession;
};

export function projectHomepage(
  roots: {
    page: ReturnType<typeof pageAri>;
    session: ReturnType<typeof userSessionAri>;
  },
  contentMap: ContentMap<ContentRegistry>,
  args: {
    params: HomepageParams;
  },
): HomepageResult {
  const memo = new Map<string, unknown>();

  const projectOnPage = (resource: any, payload: any): any => {
    const shell: any = {};
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.title = payload.title;
    return shell;
  };

  const projectOnUserSession = (resource: any, payload: any): any => {
    const shell: any = {};
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.userId = payload.userId;
    return shell;
  };

  const projectNode = (ari: any): unknown => {
    const key = ari.toString();
    if (memo.has(key)) return memo.get(key);
    const payload = contentMap.get(ari as never);
    if (payload === undefined) return undefined;
    switch (ari.type) {
      case "Page":
        return projectOnPage(ari, payload);
      case "UserSession":
        return projectOnUserSession(ari, payload);
      default:
        throw new Error(
          "projectHomepage: unexpected resource type " + JSON.stringify(ari.type)
        );
    }
  };

  return {
    page: projectNode(roots.page),
    session: projectNode(roots.session),
  } as HomepageResult;
}
`;

describe("generateProjections golden", () => {
  it("post-detail.ziel → projectPostDetail with author alias restored", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("post-detail.ziel"),
      "file:///fixtures/post-detail.ziel"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateProjections(program!);
    expectOnlyZielRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(POST_DETAIL_PROJECTION_GOLDEN));

    expect(code).toContain("export type PostDetail_Post");
    expect(code).toContain("export type PostDetail_User");
    expect(code).toContain("export type PostDetailResult = PostDetail_Post");
    expect(code).toContain("shell.author = projectNode(userAri({ id: payload.authorId }));");
    expect(code).toContain("const memo = new Map<string, unknown>();");
    expect(code).toContain("if (memo.has(key)) return memo.get(key);");
    expect(code).not.toContain(".when(");
    expect(code).not.toContain("islands");
  });

  it("page-detail.ziel → multi-resource types + Entry strips + tabs collection", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("page-detail.ziel"),
      "file:///fixtures/page-detail.ziel"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateProjections(program!);
    expectOnlyZielRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(PAGE_DETAIL_PROJECTION_GOLDEN));

    expect(code).toContain("strips: PageDetail_Entry[];");
    expect(code).toContain("related: (PageDetail_Entry | PageDetail_Asset)[];");
    expect(code).toContain("tabs: PageDetail_Entry[];");
    expect(code).toContain("export type PageDetail_Entry_Hero = {");
    expect(code).toContain("export type PageDetail_Entry_Default = {");
    expect(code).not.toContain("export type PageDetail_Entry_Page = {");
    expect(code).not.toContain("export type PageDetail_Entry_Product = {");
    expect(code).not.toContain('case "EditorialModule":');
    expect(code).toContain(
      "payload.strips.map((pageLink: any) => projectNode(entryAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: pageLink.id, locale: resource.key[0].locale })))"
    );
    expect(code).toContain(
      "payload.tabs.map((tabLink: any) => projectNode(entryAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: tabLink.id, locale: resource.key[0].locale })))"
    );
    expect(code).toContain('case "Entry":');
    expect(code).toContain('case "CustomReference":');
    expect(code).toContain("const canonical = args.redirects.get(ari.toString());");
    expect(code).toContain("const projectOnEntry = (resource: any, payload: any): any => {");
    expect(code).not.toContain("PageDetail_EditorialModule");
    expect(code).not.toContain("TabCollection");
    expect(code).not.toContain("PageDetail_Hero");
    expect(code).not.toContain(".build()");
    expect(code).not.toContain("islands");
  });

  it("homepage-multi.ziel → alias-keyed HomepageResult + projectHomepage(roots)", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("homepage-multi.ziel"),
      "file:///fixtures/homepage-multi.ziel"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateProjections(program!);
    expectOnlyZielRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(HOMEPAGE_MULTI_PROJECTION_GOLDEN));

    expect(code).toContain("export type HomepageResult = {");
    expect(code).toContain("page: Homepage_Page;");
    expect(code).toContain("session: Homepage_UserSession;");
    expect(code).toContain("roots: {\n    page: ReturnType<typeof pageAri>;");
    expect(code).toContain("page: projectNode(roots.page),");
    expect(code).toContain("session: projectNode(roots.session),");
    expect(code).not.toContain("root: ReturnType<typeof");
    expect(code).not.toContain("export type HomepageResult = Homepage_");
  });
});
