/**
 * Projection codegen entry: checked `Program` → TypeScript source string.
 * Emits query-scoped projection types + memoized `project*` materializers.
 * Generated code imports runtime only from `@xndrjs/ziel`.
 *
 * Params / context types are assumed to already exist when this module is
 * composed after strategies; the focused entry emits types + projectors only.
 */
import type { Program } from "../../../ir";
import { analyzeProgram, type ProgramAnalysis } from "../../../check";
import { emitProjectionTypes, emitProjections } from "../projections";

const GENERATED_HEADER = "/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */";

const DEFAULT_IMPORT_FROM = "@xndrjs/ziel";
const DEFAULT_REGISTRY_TYPE_NAME = "ContentRegistry";

export type GenerateProjectionsOptions = {
  /** Module specifier for `ContentMap` import. Default: `@xndrjs/ziel`. */
  importFrom?: string;
  /** Name of the registry type used as the `ContentMap` generic. Default: `ContentRegistry`. */
  registryTypeName?: string;
  /**
   * Optional property name stamped with the resource name on projection shells
   * and types (e.g. `"$type"` or `"__resource"`). Default: unset (no stamp).
   */
  resourceTag?: string;
};

export type GenerateProjectionsResult = {
  /** Full TypeScript module source. */
  code: string;
};

type ResolvedOptions = {
  importFrom: string;
  registryTypeName: string;
  resourceTag: string | undefined;
};

function resolveOptions(options?: GenerateProjectionsOptions): ResolvedOptions {
  return {
    importFrom: options?.importFrom ?? DEFAULT_IMPORT_FROM,
    registryTypeName: options?.registryTypeName ?? DEFAULT_REGISTRY_TYPE_NAME,
    resourceTag: options?.resourceTag,
  };
}

function emitRuntimeImport(importFrom: string, analysis: ProgramAnalysis): string {
  const symbols = ["type ContentMap", "type ApplicationResourceIdentifier"];
  if (analysis.queries.some((query) => query.hasRedirects)) {
    symbols.push("type ResourceKey");
  }
  if (analysis.queries.some((query) => query.needsFailureProjection)) {
    if (!symbols.includes("type ResourceKey")) {
      symbols.push("type ResourceKey");
    }
    if (!symbols.includes("type ResolutionError") && !symbols.includes("ResolutionError")) {
      symbols.push("type ResolutionError");
    }
    symbols.push("toResolutionErrorData");
  }
  if (analysis.queries.some((query) => query.usesSetError)) {
    symbols.push("type ResolutionErrorData");
  }
  return `import { ${symbols.join(", ")} } from ${JSON.stringify(importFrom)};`;
}

/**
 * Generate TypeScript source for query projection types and `project*` functions.
 *
 * Input should already be checked (`checkProgram` / `parseAndCheck`).
 * Output is a pure string (no filesystem writes). Params / context types are
 * not emitted here (see {@link generateStrategies} / compose).
 */
export function generateProjections(
  program: Program,
  options?: GenerateProjectionsOptions
): GenerateProjectionsResult {
  const { importFrom, registryTypeName, resourceTag } = resolveOptions(options);
  const analysis = analyzeProgram(program);

  const bodyParts: string[] = [];

  const types = emitProjectionTypes(analysis, resourceTag);
  if (types.length > 0) {
    bodyParts.push(types);
  }

  const projectors = emitProjections(analysis, registryTypeName, resourceTag);
  if (projectors.length > 0) {
    bodyParts.push(projectors);
  }

  const parts: string[] = [GENERATED_HEADER];

  if (bodyParts.length > 0) {
    parts.push(emitRuntimeImport(importFrom, analysis));
    parts.push(...bodyParts);
  }

  return { code: `${parts.join("\n\n")}\n` };
}
