/**
 * Resource codegen entry: checked `Program` → TypeScript source string.
 * Emits branded scalars, opaque tokens, ARI factories, payload types, and a
 * registry slice. Queries are ignored. Generated code imports runtime only
 * from `@xndrjs/ziel`.
 */
import type { Program } from "../../../ir";
import {
  emitOpaques,
  emitPayloadTypes,
  emitRegistry,
  emitResources,
  emitScalars,
} from "../resources";

const GENERATED_HEADER = "/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */";

const DEFAULT_IMPORT_FROM = "@xndrjs/ziel";
const DEFAULT_REGISTRY_TYPE_NAME = "ContentRegistry";

export type GenerateResourcesOptions = {
  /** Module specifier for runtime imports. Default: `@xndrjs/ziel`. */
  importFrom?: string;
  /** Name of the emitted registry type. Default: `ContentRegistry`. */
  registryTypeName?: string;
};

export type GenerateResourcesResult = {
  /** Full TypeScript module source. */
  code: string;
};

type ResolvedOptions = {
  importFrom: string;
  registryTypeName: string;
};

function resolveOptions(options?: GenerateResourcesOptions): ResolvedOptions {
  return {
    importFrom: options?.importFrom ?? DEFAULT_IMPORT_FROM,
    registryTypeName: options?.registryTypeName ?? DEFAULT_REGISTRY_TYPE_NAME,
  };
}

function emitRuntimeImport(importFrom: string, symbols: string[]): string {
  return `import { ${symbols.join(", ")} } from ${JSON.stringify(importFrom)};`;
}

/**
 * Generate TypeScript source for resource definitions in `program`.
 *
 * Input should already be checked (`checkProgram` / `parseAndCheck`).
 * Queries are ignored. Output is a pure string (no filesystem writes).
 *
 * Section order: scalars → opaques → ARI/resources → payload → ContentRegistry.
 */
export function generateResources(
  program: Program,
  options?: GenerateResourcesOptions
): GenerateResourcesResult {
  const { importFrom, registryTypeName } = resolveOptions(options);

  const bodyParts: string[] = [];

  const scalars = emitScalars(program);
  if (scalars.length > 0) {
    bodyParts.push(scalars);
  }

  const opaques = emitOpaques(program);
  if (opaques.length > 0) {
    bodyParts.push(opaques);
  }

  const resources = emitResources(program);
  if (resources.length > 0) {
    bodyParts.push(resources);
  }

  const payloadTypes = emitPayloadTypes(program);
  if (payloadTypes.length > 0) {
    bodyParts.push(payloadTypes);
  }

  const registry = emitRegistry(program, registryTypeName);
  if (registry.length > 0) {
    bodyParts.push(registry);
  }

  const importSymbols: string[] = [];
  if (resources.length > 0) {
    importSymbols.push("ari", "s");
  }
  if (opaques.length > 0) {
    importSymbols.push("defineOpaqueType", "type OpaqueValueOf");
  }

  const parts: string[] = [GENERATED_HEADER];

  if (importSymbols.length > 0) {
    parts.push(emitRuntimeImport(importFrom, importSymbols));
  }

  parts.push(...bodyParts);

  return { code: `${parts.join("\n\n")}\n` };
}
