import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  arg,
  construct,
  ctx,
  eq,
  expand,
  expandEach,
  field,
  item,
  lit,
  param,
  payload,
  projection,
  query,
  resource,
  scalarRef,
} from "../../../fixtures";
import type { Program } from "../../../ir";
import { parseAndCheck } from "../../parse-and-check";
import { emitStrategies } from "./emit-strategies";
import { generateStrategies } from "../generators/generate-strategies";

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), "../../../fixtures");

function loadFixture(name: string): string {
  return readFileSync(join(fixturesDir, name), "utf8");
}

function emptyProgram(): Program {
  return { scalars: [], resources: [], queries: [], span: null };
}

describe("emitStrategies", () => {
  it("returns empty string when there are no queries", () => {
    expect(emitStrategies(emptyProgram())).toBe("");
  });

  it("skips projections with no expansions and leaves the builder open", () => {
    const program: Program = {
      ...emptyProgram(),
      scalars: [],
      resources: [
        resource("Post", [field("id", scalarRef("PostId"))], {
          kind: "object",
          fields: [field("authorId", scalarRef("UserId"))],
          span: null,
        }),
        resource("User", [field("id", scalarRef("UserId"))], {
          kind: "object",
          fields: [],
          span: null,
        }),
      ],
      queries: [
        query("PostDetail", {
          parameters: [field("postId", scalarRef("PostId"))],
          context: [field("locale", scalarRef("Locale"))],
          root: construct("Post", [arg("id", param("postId"))]),
          projections: [
            projection(
              "Post",
              "p",
              ["id"],
              [expand("author", construct("User", [arg("id", payload("p", "authorId"))]))]
            ),
            projection("User", "u", ["id"]),
          ],
        }),
      ],
    };

    const code = emitStrategies(program);

    expect(code).toContain("export type PostDetailParams");
    expect(code).toContain("export type PostDetailExecutionContext");
    expect(code).toContain("export function createPostDetailStrategy(params: PostDetailParams)");
    expect(code).toContain(".on(postAri)");
    expect(code).toContain("userAri({ id: payload.authorId })");
    expect(code).not.toContain(".on(userAri)");
    expect(code).not.toContain(".build()");
    expect(code).not.toContain(".when(");
    expect(code).not.toContain("islands");
    expect(code).toMatch(/return strategy;\s*}/);
  });

  it("emits each-arm filter+map and multi-arm concat", () => {
    const program: Program = {
      ...emptyProgram(),
      queries: [
        query("PageDetail", {
          parameters: [],
          context: [field("locale", scalarRef("Locale"))],
          root: construct("Page", []),
          projections: [
            projection(
              "Page",
              "p",
              ["id"],
              [
                expandEach("strips", "s", payload("p", "strips"), [
                  {
                    target: construct("Hero", [
                      arg("id", item("s", "id")),
                      arg("locale", ctx("locale")),
                    ]),
                    when: eq(item("s", "type"), lit("Hero")),
                  },
                ]),
              ]
            ),
          ],
        }),
      ],
    };

    const code = emitStrategies(program);

    expect(code).toContain("export function createPageDetailStrategy()");
    expect(code).toContain(
      'payload.strips.filter((s: any) => s.type == "Hero").map((s: any) => heroAri({ id: s.id, locale: executionContext.locale }))'
    );
  });
});

describe("generateStrategies", () => {
  it("wraps strategies with header + createGraphResolutionStrategy import", () => {
    const { program, diagnostics } = parseAndCheck(loadFixture("post-detail.naviql"));
    expect(diagnostics).toEqual([]);

    const { code } = generateStrategies(program!);

    expect(code).toMatch(/^\/\* Generated by @xndrjs\/naviql\/compile\./);
    expect(code).toContain('import { createGraphResolutionStrategy } from "@xndrjs/naviql";');
    expect(code).not.toMatch(/from\s+["']@xndrjs\/naviql\/compile["']/);
    expect(code).toContain("createPostDetailStrategy");
    expect(code).toContain("userAri({ id: payload.authorId })");
    expect(code).not.toContain(".build()");
  });

  it("emits multi-arm each strips, collection fan-out, and concrete on blocks for page-detail", () => {
    const { program, diagnostics } = parseAndCheck(loadFixture("page-detail.naviql"));
    expect(diagnostics).toEqual([]);

    const { code } = generateStrategies(program!);

    expect(code).toContain(".on(pageAri)");
    expect(code).toContain("menuAri({ id: payload.menuId, locale: executionContext.locale })");
    expect(code).toContain("footerAri({ id: payload.footerId, locale: executionContext.locale })");
    expect(code).toContain("payload.strips.flatMap((s: any): any[] =>");
    expect(code).toContain(
      'if (s.type == "Hero") return [heroAri({ id: s.id, locale: executionContext.locale })];'
    );
    expect(code).toContain(
      'if (s.type == "Tabs") return [tabsAri({ id: s.id, locale: executionContext.locale })];'
    );
    expect(code).toContain(
      'if (s.type == "Product") return [productAri({ id: s.id, locale: executionContext.locale })];'
    );
    expect(code).toContain(".on(heroAri)");
    expect(code).toContain(".on(tabsAri)");
    expect(code).toContain(
      "tabCollectionAri({ tabsId: payload.id, locale: executionContext.locale })"
    );
    expect(code).toContain(".on(tabCollectionAri)");
    expect(code).toContain(
      "payload.map((item: any) => tabAri({ id: item.id, locale: executionContext.locale }))"
    );
    expect(code).toContain(".on(tabAri)");
    expect(code).not.toContain("editorialModuleAri");
    expect(code).not.toContain(".build()");
    expect(code).not.toContain("islands");
  });

  it("omits import when there are no queries", () => {
    const { code } = generateStrategies(emptyProgram());
    expect(code).toBe("/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */\n");
  });
});
