/**
 * Golden tests: fixture → parseAndCheck → generateStrategies → stable TypeScript source.
 * Covers open create*Strategy builders (no .build() / islands / .when()).
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { parseAndCheck } from "../../parse-and-check";
import { generateStrategies } from "./generate-strategies";

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), "../../../fixtures");

function loadFixture(name: string): string {
  return readFileSync(join(fixturesDir, name), "utf8");
}

function normalizeWhitespace(code: string): string {
  return code.trim().replace(/\n{3,}/g, "\n\n");
}

/** Collect module specifiers from top-level `import … from "…"` / `'…'`. */
function importSpecifiers(code: string): string[] {
  const specs: string[] = [];
  const re = /^\s*import\s+[\s\S]*?\s+from\s+["']([^"']+)["']/gm;
  for (const match of code.matchAll(re)) {
    specs.push(match[1]!);
  }
  return specs;
}

function expectOnlyNaviqlRuntimeImport(code: string): void {
  const specs = importSpecifiers(code);
  expect(specs).toEqual(["@xndrjs/naviql"]);
  expect(code).toContain('import { createGraphResolutionStrategy } from "@xndrjs/naviql";');
  expect(code).not.toMatch(/from\s+["']@xndrjs\/naviql\/compile["']/);
}

const POST_DETAIL_STRATEGY_GOLDEN = `
/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */

import { createGraphResolutionStrategy } from "@xndrjs/naviql";

export type PostDetailParams = {
  postId: PostId;
};

export type PostDetailExecutionContext = {
  locale: Locale;
};

export function createPostDetailStrategy(params: PostDetailParams) {
  const strategy = createGraphResolutionStrategy<
    PostDetailExecutionContext,
    ContentRegistry
  >();

  strategy.expansion
    .on(postAri)
    .expand(({ resource, payload, executionContext }) => ({
      resources: [userAri({ id: payload.authorId })],
    }));

  return strategy;
}
`;

const PAGE_DETAIL_STRATEGY_GOLDEN = `
/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */

import { createGraphResolutionStrategy } from "@xndrjs/naviql";

export type PageDetailParams = {
  pageId: PageId;
};

export type PageDetailExecutionContext = {
  locale: Locale;
};

export function createPageDetailStrategy(params: PageDetailParams) {
  const strategy = createGraphResolutionStrategy<
    PageDetailExecutionContext,
    ContentRegistry
  >();

  strategy.expansion
    .on(pageAri)
    .expand(({ resource, payload, executionContext }) => ({
      resources: [
        menuAri({ id: payload.menuId, locale: executionContext.locale }),
        footerAri({ id: payload.footerId, locale: executionContext.locale }),
        ...payload.strips.map((s) => editorialModuleAri({ id: s.id, locale: executionContext.locale })),
      ],
    }));

  strategy.expansion
    .on(heroAri)
    .expand(({ resource, payload, executionContext }) => ({
      resources: [assetAri({ id: payload.imageId, locale: executionContext.locale })],
    }));

  strategy.expansion
    .on(menuAri)
    .expand(({ resource, payload, executionContext }) => ({
      resources: [assetAri({ id: payload.logoId, locale: executionContext.locale })],
    }));

  strategy.expansion
    .on(footerAri)
    .expand(({ resource, payload, executionContext }) => ({
      resources: [assetAri({ id: payload.logoId, locale: executionContext.locale })],
    }));

  strategy.expansion
    .on(tabsAri)
    .expand(({ resource, payload, executionContext }) => ({
      resources: [tabCollectionAri({ tabsId: payload.id, locale: executionContext.locale })],
    }));

  strategy.expansion
    .on(tabAri)
    .expand(({ resource, payload, executionContext }) => ({
      resources: payload.strips.map((s) => editorialModuleAri({ id: s.id, locale: executionContext.locale })),
    }));

  return strategy;
}
`;

describe("generateStrategies golden", () => {
  it("post-detail.naviql → createPostDetailStrategy with author expansion", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("post-detail.naviql"),
      "file:///fixtures/post-detail.naviql"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateStrategies(program!);
    expectOnlyNaviqlRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(POST_DETAIL_STRATEGY_GOLDEN));

    expect(code).toContain("userAri({ id: payload.authorId })");
    expect(code).not.toContain(".on(userAri)");
    expect(code).not.toContain(".build()");
    expect(code).not.toContain(".when(");
    expect(code).not.toContain("islands");
  });

  it("page-detail.naviql → multi-.on + many map for strips", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("page-detail.naviql"),
      "file:///fixtures/page-detail.naviql"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateStrategies(program!);
    expectOnlyNaviqlRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(PAGE_DETAIL_STRATEGY_GOLDEN));

    // Spot-check nested expands the golden must cover.
    expect(code).toContain(".on(pageAri)");
    expect(code).toContain(".on(heroAri)");
    expect(code).toContain(".on(menuAri)");
    expect(code).toContain(".on(footerAri)");
    expect(code).toContain(".on(tabsAri)");
    expect(code).toContain(".on(tabAri)");
    expect(code).toContain(
      "...payload.strips.map((s) => editorialModuleAri({ id: s.id, locale: executionContext.locale }))"
    );
    expect(code).not.toContain(".on(assetAri)");
    expect(code).not.toContain(".on(productAri)");
    expect(code).not.toContain(".build()");
    expect(code).not.toContain("islands");
  });
});
