/**
 * Golden tests: fixture → parseAndCheck → generateProjections → stable TypeScript source.
 * Covers query-scoped `$type` aggregates, alias restoration, and memoized `project*`.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { parseAndCheck } from "../../parse-and-check";
import { generateProjections } from "./generate-projections";

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), "../../../fixtures");

function loadFixture(name: string): string {
  return readFileSync(join(fixturesDir, name), "utf8");
}

function normalizeWhitespace(code: string): string {
  return code.trim().replace(/\n{3,}/g, "\n\n");
}

/** Collect module specifiers from top-level `import … from "…"` / `'…'`. */
function importSpecifiers(code: string): string[] {
  const specs: string[] = [];
  const re = /^\s*import\s+[\s\S]*?\s+from\s+["']([^"']+)["']/gm;
  for (const match of code.matchAll(re)) {
    specs.push(match[1]!);
  }
  return specs;
}

function expectOnlyNaviqlRuntimeImport(code: string): void {
  const specs = importSpecifiers(code);
  expect(specs).toEqual(["@xndrjs/naviql"]);
  expect(code).toContain('import { type ContentMap } from "@xndrjs/naviql";');
  expect(code).not.toMatch(/from\s+["']@xndrjs\/naviql\/compile["']/);
}

const POST_DETAIL_PROJECTION_GOLDEN = `/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */

import { type ContentMap } from "@xndrjs/naviql";

export type PostDetail_Post = {
  $type: "Post";
  id: PostId;
  title: string;
  content: string;
  author: PostDetail_User;
};

export type PostDetail_User = {
  $type: "User";
  id: UserId;
  username: string;
};

export type PostDetailResult = PostDetail_Post;

export function projectPostDetail(
  root: ReturnType<typeof postAri>,
  contentMap: ContentMap<ContentRegistry>,
  args: {
    params: PostDetailParams;
    executionContext: PostDetailExecutionContext;
  },
): PostDetailResult {
  const { params, executionContext } = args;
  const memo = new Map<string, object>();

  const projectOnPost = (resource: any, payload: any): any => {
    const shell: any = { $type: "Post" };
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.title = payload.title;
    shell.content = payload.content;
    shell.author = projectNode(userAri({ id: payload.authorId }));
    return shell;
  };

  const projectOnUser = (resource: any, payload: any): any => {
    const shell: any = { $type: "User" };
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.username = payload.username;
    return shell;
  };

  const projectNode = (ari: any): unknown => {
    const key = ari.toString();
    if (memo.has(key)) return memo.get(key);
    const payload = contentMap.get(ari as never);
    if (payload === undefined) return undefined;
    switch (ari.type) {
      case "Post":
        return projectOnPost(ari, payload);
      case "User":
        return projectOnUser(ari, payload);
      default:
        throw new Error(
          "projectPostDetail: unexpected resource type " + JSON.stringify(ari.type)
        );
    }
  };

  return projectNode(root) as PostDetailResult;
}
`;

const PAGE_DETAIL_PROJECTION_GOLDEN = `/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */

import { type ContentMap } from "@xndrjs/naviql";

export type PageDetail_Page = {
  $type: "Page";
  id: EntryId;
  title: string;
  menu: PageDetail_Menu;
  footer: PageDetail_Footer;
  strips: (PageDetail_Hero | PageDetail_Tabs | PageDetail_Product)[];
  related: (PageDetail_Hero | PageDetail_Tabs | PageDetail_Product | PageDetail_Asset)[];
};

export type PageDetail_Hero = {
  $type: "Hero";
  id: EntryId;
  title: string;
  image: PageDetail_Asset;
};

export type PageDetail_Menu = {
  $type: "Menu";
  id: EntryId;
  title: string;
  logo: PageDetail_Asset;
};

export type PageDetail_Footer = {
  $type: "Footer";
  id: EntryId;
  title: string;
  logo: PageDetail_Asset;
};

export type PageDetail_Asset = {
  $type: "Asset";
  id: AssetId;
  url: string;
  title: string;
  kind: "image" | "video" | "document";
};

export type PageDetail_Tabs = {
  $type: "Tabs";
  id: EntryId;
  title: string;
  tabs: PageDetail_Tab[];
};

export type PageDetail_Tab = {
  $type: "Tab";
  id: EntryId;
  title: string;
  strips: (PageDetail_Hero | PageDetail_Tabs | PageDetail_Product)[];
};

export type PageDetail_Product = {
  $type: "Product";
  id: EntryId;
  sku: Sku;
  title: string;
};

export type PageDetailResult = PageDetail_Page;

export function projectPageDetail(
  root: ReturnType<typeof pageAri>,
  contentMap: ContentMap<ContentRegistry>,
  args: {
    params: PageDetailParams;
    executionContext: PageDetailExecutionContext;
  },
): PageDetailResult {
  const { params, executionContext } = args;
  const memo = new Map<string, object>();

  const projectOnPage = (resource: any, payload: any): any => {
    const shell: any = { $type: "Page" };
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.title = payload.title;
    shell.menu = projectNode(menuAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: payload.menuId, locale: resource.key[0].locale }));
    shell.footer = projectNode(footerAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: payload.footerId, locale: resource.key[0].locale }));
    shell.strips = payload.strips.map((link: any) => projectNode(entryAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: link.id, locale: resource.key[0].locale })));
    shell.related = payload.related.map((ref: any) => projectNode(customReferenceAri({ ref: ref, locale: resource.key[0].locale })));
    return shell;
  };

  const projectOnHero = (resource: any, payload: any): any => {
    const shell: any = { $type: "Hero" };
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.title = payload.title;
    shell.image = projectNode(assetAri({ spaceId: executionContext.spaceId, environmentId: executionContext.environmentId, id: payload.imageId, locale: resource.key[0].locale }));
    return shell;
  };

  const projectOnMenu = (resource: any, payload: any): any => {
    const shell: any = { $type: "Menu" };
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.title = payload.title;
    shell.logo = projectNode(assetAri({ spaceId: executionContext.spaceId, environmentId: executionContext.environmentId, id: payload.logoId, locale: resource.key[0].locale }));
    return shell;
  };

  const projectOnFooter = (resource: any, payload: any): any => {
    const shell: any = { $type: "Footer" };
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.title = payload.title;
    shell.logo = projectNode(assetAri({ spaceId: executionContext.spaceId, environmentId: executionContext.environmentId, id: payload.logoId, locale: resource.key[0].locale }));
    return shell;
  };

  const projectOnAsset = (resource: any, payload: any): any => {
    const shell: any = { $type: "Asset" };
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.url = payload.url;
    shell.title = payload.title;
    shell.kind = payload.kind;
    return shell;
  };

  const projectOnTabs = (resource: any, payload: any): any => {
    const shell: any = { $type: "Tabs" };
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.title = payload.title;
    shell.tabs = payload.tabs.map((link: any) => projectNode(tabAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: link.id, locale: resource.key[0].locale })));
    return shell;
  };

  const projectOnTab = (resource: any, payload: any): any => {
    const shell: any = { $type: "Tab" };
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.title = payload.title;
    shell.strips = payload.strips.map((link: any) => projectNode(entryAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: link.id, locale: resource.key[0].locale })));
    return shell;
  };

  const projectOnProduct = (resource: any, payload: any): any => {
    const shell: any = { $type: "Product" };
    memo.set(resource.toString(), shell);
    shell.id = payload.id;
    shell.sku = payload.sku;
    shell.title = payload.title;
    return shell;
  };

  const projectNode = (ari: any): unknown => {
    const key = ari.toString();
    if (memo.has(key)) return memo.get(key);
    const payload = contentMap.get(ari as never);
    if (payload === undefined) return undefined;
    switch (ari.type) {
      case "Page":
        return projectOnPage(ari, payload);
      case "Hero":
        return projectOnHero(ari, payload);
      case "Menu":
        return projectOnMenu(ari, payload);
      case "Footer":
        return projectOnFooter(ari, payload);
      case "Asset":
        return projectOnAsset(ari, payload);
      case "Tabs":
        return projectOnTabs(ari, payload);
      case "Tab":
        return projectOnTab(ari, payload);
      case "Product":
        return projectOnProduct(ari, payload);
      case "Entry": {
        switch ((payload as any).type) {
          case "Hero":
            return projectOnHero(ari, payload);
          case "Tabs":
            return projectOnTabs(ari, payload);
          case "Product":
            return projectOnProduct(ari, payload);
          default:
            throw new Error(
              "projectPageDetail: cannot discriminate Entry payload (type=" +
                JSON.stringify((payload as any).type) +
                ")"
            );
        }
      }
      case "CustomReference": {
        switch ((payload as any).type) {
          case "Hero":
            return projectOnHero(ari, payload);
          case "Tabs":
            return projectOnTabs(ari, payload);
          case "Product":
            return projectOnProduct(ari, payload);
          case "Asset":
            return projectOnAsset(ari, payload);
          default:
            throw new Error(
              "projectPageDetail: cannot discriminate CustomReference payload (type=" +
                JSON.stringify((payload as any).type) +
                ")"
            );
        }
      }
      default:
        throw new Error(
          "projectPageDetail: unexpected resource type " + JSON.stringify(ari.type)
        );
    }
  };

  return projectNode(root) as PageDetailResult;
}
`;

describe("generateProjections golden", () => {
  it("post-detail.naviql → projectPostDetail with author alias restored", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("post-detail.naviql"),
      "file:///fixtures/post-detail.naviql"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateProjections(program!);
    expectOnlyNaviqlRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(POST_DETAIL_PROJECTION_GOLDEN));

    expect(code).toContain("export type PostDetail_Post");
    expect(code).toContain("export type PostDetail_User");
    expect(code).toContain("export type PostDetailResult = PostDetail_Post");
    expect(code).toContain("shell.author = projectNode(userAri({ id: payload.authorId }));");
    expect(code).toContain("const memo = new Map<string, object>();");
    expect(code).toContain("if (memo.has(key)) return memo.get(key);");
    expect(code).not.toContain(".when(");
    expect(code).not.toContain("islands");
  });

  it("page-detail.naviql → multi-resource types + Entry strips + tabs collection", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("page-detail.naviql"),
      "file:///fixtures/page-detail.naviql"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateProjections(program!);
    expectOnlyNaviqlRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(PAGE_DETAIL_PROJECTION_GOLDEN));

    expect(code).toContain("strips: (PageDetail_Hero | PageDetail_Tabs | PageDetail_Product)[];");
    expect(code).toContain(
      "related: (PageDetail_Hero | PageDetail_Tabs | PageDetail_Product | PageDetail_Asset)[];"
    );
    expect(code).toContain("tabs: PageDetail_Tab[];");
    expect(code).not.toContain('case "EditorialModule":');
    expect(code).toContain(
      "payload.strips.map((link: any) => projectNode(entryAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: link.id, locale: resource.key[0].locale })))"
    );
    expect(code).toContain(
      "payload.tabs.map((link: any) => projectNode(tabAri({ spaceId: resource.key[0].spaceId, environmentId: resource.key[0].environmentId, id: link.id, locale: resource.key[0].locale })))"
    );
    expect(code).toContain('case "Entry":');
    expect(code).toContain('case "CustomReference":');
    expect(code).not.toContain("PageDetail_EditorialModule");
    expect(code).not.toContain("TabCollection");
    expect(code).not.toContain(".build()");
    expect(code).not.toContain("islands");
  });
});
