/**
 * Golden tests: fixture → parseAndCheck → generateStrategies → stable TypeScript source.
 * Covers open create*Strategy builders (no .build() / islands). Flat fixtures omit `.when(`.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { parseAndCheck } from "../../parse-and-check";
import { generateStrategies } from "./generate-strategies";

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), "../../../fixtures");

function loadFixture(name: string): string {
  return readFileSync(join(fixturesDir, name), "utf8");
}

function normalizeWhitespace(code: string): string {
  return code.trim().replace(/\n{3,}/g, "\n\n");
}

/** Collect module specifiers from top-level `import … from "…"` / `'…'`. */
function importSpecifiers(code: string): string[] {
  const specs: string[] = [];
  const re = /^\s*import\s+[\s\S]*?\s+from\s+["']([^"']+)["']/gm;
  for (const match of code.matchAll(re)) {
    specs.push(match[1]!);
  }
  return specs;
}

function expectOnlyNaviqlRuntimeImport(code: string): void {
  const specs = importSpecifiers(code);
  expect(specs).toEqual(["@xndrjs/naviql"]);
  expect(code).toContain('import { createGraphResolutionStrategy } from "@xndrjs/naviql";');
  expect(code).not.toMatch(/from\s+["']@xndrjs\/naviql\/compile["']/);
}

const POST_DETAIL_STRATEGY_GOLDEN = `
/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */

import { createGraphResolutionStrategy } from "@xndrjs/naviql";

export type PostDetailParams = {
  postId: PostId;
};

export type PostDetailExecutionContext = {
  locale: Locale;
};

export function createPostDetailStrategy(params: PostDetailParams) {
  const strategy = createGraphResolutionStrategy<
    PostDetailExecutionContext,
    ContentRegistry
  >();

  strategy.expansion
    .on(postAri)
    .expand((predicate) => ({
      resources: [userAri({ id: predicate.payload.authorId })],
    }));

  return strategy;
}
`;

const PAGE_DETAIL_STRATEGY_GOLDEN = `
/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */

import { createGraphResolutionStrategy } from "@xndrjs/naviql";

export type PageDetailParams = {
  pageId: EntryId;
};

export type PageDetailExecutionContext = {
  spaceId: SpaceId;
  environmentId: EnvironmentId;
  locale: Locale;
};

export function createPageDetailStrategy(params: PageDetailParams) {
  const strategy = createGraphResolutionStrategy<
    PageDetailExecutionContext,
    ContentRegistry
  >();

  strategy.expansion
    .on(pageAri)
    .expand((predicate) => ({
      resources: [
        entryAri({ spaceId: predicate.resource.key[0].spaceId, environmentId: predicate.resource.key[0].environmentId, id: predicate.payload.menuId, locale: predicate.resource.key[0].locale }),
        entryAri({ spaceId: predicate.resource.key[0].spaceId, environmentId: predicate.resource.key[0].environmentId, id: predicate.payload.footerId, locale: predicate.resource.key[0].locale }),
        ...predicate.payload.strips.map((link: any) => entryAri({ spaceId: predicate.resource.key[0].spaceId, environmentId: predicate.resource.key[0].environmentId, id: link.id, locale: predicate.resource.key[0].locale })),
        ...predicate.payload.related.map((ref: any) => customReferenceAri({ ref: ref, locale: predicate.resource.key[0].locale })),
      ],
    }));

  strategy.expansion
    .on(entryAri)
    .when((predicate) => predicate.payload.type == "Hero")
    .expand((predicate) => {
      const payload = predicate.payload as any;
      return {
        resources: [assetAri({ spaceId: predicate.executionContext.spaceId, environmentId: predicate.executionContext.environmentId, id: payload.imageId, locale: predicate.resource.key[0].locale })],
      };
    });

  strategy.expansion
    .on(entryAri)
    .when((predicate) => predicate.payload.type == "Tabs")
    .expand((predicate) => {
      const payload = predicate.payload as any;
      return {
        resources: payload.tabs.map((link: any) => entryAri({ spaceId: predicate.resource.key[0].spaceId, environmentId: predicate.resource.key[0].environmentId, id: link.id, locale: predicate.resource.key[0].locale })),
      };
    });

  strategy.expansion
    .on(entryAri)
    .when((predicate) => predicate.payload.type == "Tab")
    .expand((predicate) => {
      const payload = predicate.payload as any;
      return {
        resources: payload.strips.map((link: any) => entryAri({ spaceId: predicate.resource.key[0].spaceId, environmentId: predicate.resource.key[0].environmentId, id: link.id, locale: predicate.resource.key[0].locale })),
      };
    });

  strategy.expansion
    .on(entryAri)
    .when((predicate) => predicate.payload.type == "Menu")
    .expand((predicate) => {
      const payload = predicate.payload as any;
      return {
        resources: [assetAri({ spaceId: predicate.executionContext.spaceId, environmentId: predicate.executionContext.environmentId, id: payload.logoId, locale: predicate.resource.key[0].locale })],
      };
    });

  strategy.expansion
    .on(entryAri)
    .when((predicate) => predicate.payload.type == "Footer")
    .expand((predicate) => {
      const payload = predicate.payload as any;
      return {
        resources: [assetAri({ spaceId: predicate.executionContext.spaceId, environmentId: predicate.executionContext.environmentId, id: payload.logoId, locale: predicate.resource.key[0].locale })],
      };
    });

  strategy.expansion
    .on(entryAri)
    .when((predicate) => predicate.payload.type == "SiteInternalLink")
    .expand((predicate) => {
      const payload = predicate.payload as any;
      return {
        resources: [entryAri({ spaceId: predicate.resource.key[0].spaceId, environmentId: predicate.resource.key[0].environmentId, id: payload.targetId, locale: predicate.resource.key[0].locale })],
      };
    });

  strategy.resolve
    .on(customReferenceAri)
    .when((predicate) => predicate.payload.type == "Entry")
    .to((predicate) => {
      const payload = predicate.payload as any;
      return {
        resource: entryAri({ spaceId: payload.spaceId, environmentId: payload.environmentId, id: payload.id, locale: payload.locale }),
      };
    });

  strategy.resolve
    .on(customReferenceAri)
    .when((predicate) => predicate.payload.type == "Asset")
    .to((predicate) => {
      const payload = predicate.payload as any;
      return {
        resource: assetAri({ spaceId: payload.spaceId, environmentId: payload.environmentId, id: payload.id, locale: payload.locale }),
      };
    });

  return strategy;
}
`;

describe("generateStrategies golden", () => {
  it("post-detail.naviql → createPostDetailStrategy with author expansion", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("post-detail.naviql"),
      "file:///fixtures/post-detail.naviql"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateStrategies(program!);
    expectOnlyNaviqlRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(POST_DETAIL_STRATEGY_GOLDEN));

    expect(code).toContain("userAri({ id: predicate.payload.authorId })");
    expect(code).not.toContain(".on(userAri)");
    expect(code).not.toContain(".build()");
    expect(code).not.toContain(".when(");
    expect(code).not.toContain("islands");
  });

  it("page-detail.naviql → multi-.on + Entry/CustomReference map for strips", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("page-detail.naviql"),
      "file:///fixtures/page-detail.naviql"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateStrategies(program!);
    expectOnlyNaviqlRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(PAGE_DETAIL_STRATEGY_GOLDEN));

    // Spot-check nested expands the golden must cover.
    expect(code).toContain(".on(pageAri)");
    expect(code).toContain(".on(entryAri)");
    expect(code).toContain('.when((predicate) => predicate.payload.type == "Hero")');
    expect(code).toContain('.when((predicate) => predicate.payload.type == "SiteInternalLink")');
    expect(code).toContain(
      "payload.tabs.map((link: any) => entryAri({ spaceId: predicate.resource.key[0].spaceId, environmentId: predicate.resource.key[0].environmentId, id: link.id, locale: predicate.resource.key[0].locale }))"
    );
    expect(code).toContain(
      "predicate.payload.strips.map((link: any) => entryAri({ spaceId: predicate.resource.key[0].spaceId, environmentId: predicate.resource.key[0].environmentId, id: link.id, locale: predicate.resource.key[0].locale }))"
    );
    expect(code).toContain(
      "predicate.payload.related.map((ref: any) => customReferenceAri({ ref: ref, locale: predicate.resource.key[0].locale }))"
    );
    expect(code).not.toContain("editorialModuleAri");
    expect(code).not.toContain("tabCollectionAri");
    expect(code).not.toContain("heroAri");
    expect(code).not.toContain(".on(assetAri)");
    expect(code).toContain("strategy.resolve");
    expect(code).toContain(".on(customReferenceAri)");
    expect(code).toContain('.when((predicate) => predicate.payload.type == "Entry")');
    expect(code).toContain('.when((predicate) => predicate.payload.type == "Asset")');
    expect(code).toContain(
      "entryAri({ spaceId: payload.spaceId, environmentId: payload.environmentId, id: payload.id, locale: payload.locale })"
    );
    expect(code).toContain(
      "assetAri({ spaceId: payload.spaceId, environmentId: payload.environmentId, id: payload.id, locale: payload.locale })"
    );
    expect(code).not.toContain(".build()");
    expect(code).not.toContain("islands");
  });
});
