/**
 * Golden tests: fixture → parseAndCheck → generateResources → stable TypeScript source.
 * Covers branded scalars, ARI factories, payload types, and ContentRegistry.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { pageDetailProgram } from "../../../fixtures";
import { parseAndCheck } from "../../parse-and-check";
import { generateResources } from "./generate-resources";

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), "../../../fixtures");

function loadFixture(name: string): string {
  return readFileSync(join(fixturesDir, name), "utf8");
}

function normalizeWhitespace(code: string): string {
  return code.trim().replace(/\n{3,}/g, "\n\n");
}

/** Collect module specifiers from top-level `import … from "…"` / `'…'`. */
function importSpecifiers(code: string): string[] {
  const specs: string[] = [];
  const re = /^\s*import\s+[\s\S]*?\s+from\s+["']([^"']+)["']/gm;
  for (const match of code.matchAll(re)) {
    specs.push(match[1]!);
  }
  return specs;
}

function expectOnlyNaviqlRuntimeImport(code: string): void {
  const specs = importSpecifiers(code);
  expect(specs).toEqual(["@xndrjs/naviql"]);
  expect(code).toContain('import { ari, s } from "@xndrjs/naviql";');
  expect(code).not.toMatch(/from\s+["']@xndrjs\/naviql\/compile["']/);
}

const POST_DETAIL_GOLDEN = `
/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */

import { ari, s } from "@xndrjs/naviql";

declare const __brand: unique symbol;
type Branded<Name extends string, T> = T & { readonly [__brand]: Name };

export type PostId = Branded<"PostId", string>;

export type UserId = Branded<"UserId", string>;

export type Locale = Branded<"Locale", string>;

export const postAri = ari(
  "Post",
  s.object({ id: s.string(), locale: s.string() }),
);
export type PostResource = ReturnType<typeof postAri>;

export const userAri = ari(
  "User",
  s.object({ id: s.string() }),
);
export type UserResource = ReturnType<typeof userAri>;

export type PostPayload = {
  id: PostId;
  title: string;
  content: string;
  authorId: UserId;
};

export type UserPayload = {
  id: UserId;
  username: string;
};

export type ContentRegistry = {
  Post: PostPayload;
  User: UserPayload;
};
`;

const PAGE_DETAIL_GOLDEN = `
/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */

import { ari, s } from "@xndrjs/naviql";

declare const __brand: unique symbol;
type Branded<Name extends string, T> = T & { readonly [__brand]: Name };

export type Locale = Branded<"Locale", string>;

export type PageId = Branded<"PageId", string>;

export type HeroId = Branded<"HeroId", string>;

export type MenuId = Branded<"MenuId", string>;

export type FooterId = Branded<"FooterId", string>;

export type AssetId = Branded<"AssetId", string>;

export type TabsId = Branded<"TabsId", string>;

export type TabId = Branded<"TabId", string>;

export type ProductId = Branded<"ProductId", string>;

export type Sku = Branded<"Sku", string>;

export const pageAri = ari(
  "Page",
  s.object({ id: s.string(), locale: s.string() }),
);
export type PageResource = ReturnType<typeof pageAri>;

export const heroAri = ari(
  "Hero",
  s.object({ id: s.string(), locale: s.string() }),
);
export type HeroResource = ReturnType<typeof heroAri>;

export const menuAri = ari(
  "Menu",
  s.object({ id: s.string(), locale: s.string() }),
);
export type MenuResource = ReturnType<typeof menuAri>;

export const footerAri = ari(
  "Footer",
  s.object({ id: s.string(), locale: s.string() }),
);
export type FooterResource = ReturnType<typeof footerAri>;

export const assetAri = ari(
  "Asset",
  s.object({ id: s.string(), locale: s.string() }),
);
export type AssetResource = ReturnType<typeof assetAri>;

export const tabsAri = ari(
  "Tabs",
  s.object({ id: s.string(), locale: s.string() }),
);
export type TabsResource = ReturnType<typeof tabsAri>;

export const tabAri = ari(
  "Tab",
  s.object({ id: s.string(), locale: s.string() }),
);
export type TabResource = ReturnType<typeof tabAri>;

export const tabCollectionAri = ari(
  "TabCollection",
  s.object({ tabsId: s.string(), locale: s.string() }),
);
export type TabCollectionResource = ReturnType<typeof tabCollectionAri>;

export const productAri = ari(
  "Product",
  s.object({ id: s.string(), locale: s.string() }),
);
export type ProductResource = ReturnType<typeof productAri>;

export type PagePayload = {
  id: PageId;
  title: string;
  menuId: MenuId;
  footerId: FooterId;
  strips: ({
    type: "Hero";
    id: HeroId;
  } | {
    type: "Tabs";
    id: TabsId;
  } | {
    type: "Product";
    id: ProductId;
  })[];
};

export type HeroPayload = {
  type: "Hero";
  id: HeroId;
  title: string;
  imageId: AssetId;
};

export type MenuPayload = {
  id: MenuId;
  title: string;
  logoId: AssetId;
};

export type FooterPayload = {
  id: FooterId;
  title: string;
  logoId: AssetId;
};

export type AssetPayload = {
  id: AssetId;
  url: string;
  title: string;
  kind: "image" | "video" | "document";
};

export type TabsPayload = {
  type: "Tabs";
  id: TabsId;
  title: string;
};

export type TabPayload = {
  id: TabId;
  title: string;
  strips: ({
    type: "Hero";
    id: HeroId;
  } | {
    type: "Tabs";
    id: TabsId;
  } | {
    type: "Product";
    id: ProductId;
  })[];
};

export type TabCollectionPayload = TabPayload[];

export type ProductPayload = {
  type: "Product";
  id: ProductId;
  sku: Sku;
  title: string;
};

export type ContentRegistry = {
  Page: PagePayload;
  Hero: HeroPayload;
  Menu: MenuPayload;
  Footer: FooterPayload;
  Asset: AssetPayload;
  Tabs: TabsPayload;
  Tab: TabPayload;
  TabCollection: TabCollectionPayload;
  Product: ProductPayload;
};
`;

describe("generateResources golden", () => {
  it("post-detail.naviql → stable source (scalars, ARIs, payloads, registry)", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("post-detail.naviql"),
      "file:///fixtures/post-detail.naviql"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateResources(program);
    expectOnlyNaviqlRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(POST_DETAIL_GOLDEN));
  });

  it("page-detail.naviql → stable source (unions, resourceRef, typeProjection)", () => {
    const { program, diagnostics } = parseAndCheck(
      loadFixture("page-detail.naviql"),
      "file:///fixtures/page-detail.naviql"
    );
    expect(diagnostics).toEqual([]);

    const { code } = generateResources(program);
    expectOnlyNaviqlRuntimeImport(code);
    expect(normalizeWhitespace(code)).toBe(normalizeWhitespace(PAGE_DETAIL_GOLDEN));

    // Spot-check cases the golden must cover.
    expect(code).toContain("export type TabCollectionPayload = TabPayload[];");
    expect(code).not.toContain("EditorialModulePayload");
    expect(code).not.toContain("editorialModuleAri");
    expect(code).toContain(`type: "Hero"`);
    expect(code).toContain(`type: "Tabs"`);
    expect(code).toContain(`type: "Product"`);
    expect(code).not.toContain("EditorialModule.type");
    expect(code).not.toContain("typeProjection");
  });

  it("pageDetailProgram() IR path matches page-detail fixture emit (span-free)", () => {
    const fromFixture = parseAndCheck(
      loadFixture("page-detail.naviql"),
      "file:///fixtures/page-detail.naviql"
    );
    expect(fromFixture.diagnostics).toEqual([]);

    const fixtureCode = generateResources(fromFixture.program).code;
    const irCode = generateResources(pageDetailProgram()).code;

    expect(normalizeWhitespace(irCode)).toBe(normalizeWhitespace(fixtureCode));
    expect(normalizeWhitespace(irCode)).toBe(normalizeWhitespace(PAGE_DETAIL_GOLDEN));
    expectOnlyNaviqlRuntimeImport(irCode);
  });
});
