/**
 * Strategy codegen entry: checked `Program` → TypeScript source string.
 * Emits open `create*Strategy` builders (no `.build()` / root helpers).
 * Armed `on` projections emit `.when(…)`; flat `on` does not.
 * Query `islands` emit `.islands.on(…)[.when(…)].startIsland()`.
 * Generated code imports runtime only from `@xndrjs/naviql`.
 */
import type { Program } from "../../../ir";
import { emitStrategies } from "../strategies";

const GENERATED_HEADER = "/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */";

const DEFAULT_IMPORT_FROM = "@xndrjs/naviql";
const DEFAULT_REGISTRY_TYPE_NAME = "ContentRegistry";

export type GenerateStrategiesOptions = {
  /** Module specifier for `createGraphResolutionStrategy` import. Default: `@xndrjs/naviql`. */
  importFrom?: string;
  /** Name of the registry type used as the strategy generic. Default: `ContentRegistry`. */
  registryTypeName?: string;
};

export type GenerateStrategiesResult = {
  /** Full TypeScript module source. */
  code: string;
};

type ResolvedOptions = {
  importFrom: string;
  registryTypeName: string;
};

function resolveOptions(options?: GenerateStrategiesOptions): ResolvedOptions {
  return {
    importFrom: options?.importFrom ?? DEFAULT_IMPORT_FROM,
    registryTypeName: options?.registryTypeName ?? DEFAULT_REGISTRY_TYPE_NAME,
  };
}

function emitRuntimeImport(importFrom: string): string {
  return `import { createGraphResolutionStrategy } from ${JSON.stringify(importFrom)};`;
}

/**
 * Generate TypeScript source for query expansion strategies in `program`.
 *
 * Input should already be checked (`checkProgram` / `parseAndCheck`).
 * Output is a pure string (no filesystem writes). Builders are left open for
 * apps to attach extra island / `.when` policies before `.build()`.
 */
export function generateStrategies(
  program: Program,
  options?: GenerateStrategiesOptions
): GenerateStrategiesResult {
  const { importFrom, registryTypeName } = resolveOptions(options);
  const body = emitStrategies(program, registryTypeName);

  const parts: string[] = [GENERATED_HEADER];

  if (body.length > 0) {
    parts.push(emitRuntimeImport(importFrom));
    parts.push(body);
  }

  return { code: `${parts.join("\n\n")}\n` };
}
