import {
  defineConfig,
  resolveFieldLocalizationFlags,
  type ContentfulToZodConfig,
  type FieldLocalizationMode,
} from "../config/define-config";
import type { ContentField, ContentType } from "../model/content-type";
import type { Locale } from "../model/locale";
import { emitContentTypeIdPrimitives } from "./content-type-id-primitives";
import {
  collectFieldEnums,
  fieldEnumDescriptorMap,
  emitFieldEnumPrimitives,
  type FieldEnumDescriptor,
} from "./field-enum-primitives";
import {
  fieldToZod,
  flatFieldSource,
  localizedFieldSource,
  validateObjectOverrides,
  type FieldZodResult,
} from "./field-to-zod";
import { fieldsForCodegen } from "./filter-fields";
import { emitLocalePrimitives, requireLocalesForModes } from "./locale-primitives";
import { CONTENTFUL_PRIMITIVE_SCHEMA_NAMES, CONTENTFUL_PRIMITIVE_SCHEMAS } from "./primitives";
import {
  fieldsSchemaExportName,
  emitInferredType,
  localizedFieldsSchemaExportName,
} from "./schema-name";
import {
  emitAssetDeliverySchema,
  emitContentTypeLocalizedEntrySchema,
  emitEntrySysPrimitives,
} from "./entry-to-source";
import { emitLinkFieldParseHelpers } from "./emit-link-field-parse";
import { emitLinkFieldMetadata } from "./emit-link-field-metadata";
import { emitLocaleHelpers } from "./helpers-to-source";
import {
  collectLinkFields,
  collectLinkFieldTargets,
  validateLinkFieldTargets,
} from "./link-fields";
import { emitFlatFieldHelper, emitTransportFieldHelper } from "./transport-primitives";
import { zodToSource } from "./zod-to-source";

export type { FieldLocalizationMode };

export interface GenerateZodSchemasOptions {
  contentTypeIds?: string[] | undefined;
  locales?: Locale[] | undefined;
  /** Which field-localization shapes to emit. Default from config or `["flat", "localized-only"]`. */
  localeModes?: readonly FieldLocalizationMode[] | undefined;
  config?: ContentfulToZodConfig | undefined;
}

function filterContentTypes(
  contentTypes: ContentType[],
  contentTypeIds: string[] | undefined
): ContentType[] {
  if (!contentTypeIds?.length) {
    return contentTypes;
  }

  const allowed = new Set(contentTypeIds);
  const filtered = contentTypes.filter((contentType) => allowed.has(contentType.id));

  for (const id of contentTypeIds) {
    if (!filtered.some((contentType) => contentType.id === id)) {
      throw new Error(`Content type "${id}" was not found in the provided snapshot.`);
    }
  }

  return filtered;
}

function fieldSource(
  flat: FieldZodResult,
  field: ContentField,
  localization: "flat" | "localized-only"
): string {
  if (localization === "flat") {
    return flatFieldSource(flat, field);
  }

  return localizedFieldSource(flat, field);
}

function emitContentTypeSchema(
  contentType: ContentType,
  options: {
    localization: "flat" | "localized-only";
    config?: ContentfulToZodConfig | undefined;
    fieldEnums?: ReadonlyMap<string, FieldEnumDescriptor> | undefined;
  }
): string[] {
  const shapeEntries: string[] = [];

  for (const field of fieldsForCodegen(contentType.fields, options.config)) {
    const flat = fieldToZod(field, {
      contentTypeId: contentType.id,
      config: options.config,
      fieldEnums: options.fieldEnums,
    });

    shapeEntries.push(
      `  ${JSON.stringify(field.id)}: ${fieldSource(flat, field, options.localization)},`
    );
  }

  const exportName =
    options.localization === "localized-only"
      ? localizedFieldsSchemaExportName(contentType.id)
      : fieldsSchemaExportName(contentType.id);
  return [
    `export const ${exportName} = z.object({`,
    ...shapeEntries,
    "});",
    "",
    emitInferredType(exportName),
    "",
  ];
}

function emitFileHeader(): string {
  return [
    "/**",
    " * @generated by @xndrjs/contentful-to-zod",
    " * Do not edit manually.",
    " */",
    "",
    'import { z } from "zod";',
    "",
  ].join("\n");
}

function emitSharedPrimitives(): string {
  const lines = CONTENTFUL_PRIMITIVE_SCHEMA_NAMES.flatMap((name) => {
    const schema = CONTENTFUL_PRIMITIVE_SCHEMAS[name];
    return [`export const ${name} = ${zodToSource(schema)};`, emitInferredType(name), ""];
  });

  return lines.join("\n");
}

/** Generate a self-contained TypeScript module with Zod schemas for Contentful content types. */
export function generateZodSchemas(
  contentTypes: ContentType[],
  options: GenerateZodSchemasOptions = {}
): string {
  const config = options.config ? defineConfig(options.config) : undefined;
  const flags = resolveFieldLocalizationFlags({
    localeModes: options.localeModes,
    config,
  });
  // `all` (`locale=*`) shape emission lands in a follow-up; flag is accepted/validated now.
  void flags.includeAll;

  const locales = requireLocalesForModes(flags.needsLocales, options.locales);
  const selectedContentTypes = filterContentTypes(contentTypes, options.contentTypeIds);

  validateObjectOverrides(selectedContentTypes, config);

  const linkFieldTargets = collectLinkFieldTargets(selectedContentTypes, config);
  const linkFields = collectLinkFields(selectedContentTypes, config);
  const availableContentTypeIds = new Set(selectedContentTypes.map((ct) => ct.id));
  validateLinkFieldTargets(linkFieldTargets, availableContentTypeIds);

  const sections: string[] = [emitFileHeader()];

  if (flags.needsLocales && locales) {
    sections.push(emitLocalePrimitives(locales), "");
  }

  const fieldHelpers: string[] = [];
  if (flags.includeFlat) {
    fieldHelpers.push(emitFlatFieldHelper());
  }
  if (flags.includeLocalizedOnly && locales) {
    fieldHelpers.push(emitTransportFieldHelper());
  }
  if (fieldHelpers.length > 0) {
    sections.push(fieldHelpers.join("\n\n"), "");
  }

  if (flags.includeLocalizedOnly && locales) {
    sections.push(emitEntrySysPrimitives(), "", emitAssetDeliverySchema(), "");
  }

  sections.push(emitSharedPrimitives());

  const fieldEnums = collectFieldEnums(selectedContentTypes, config);
  const fieldEnumMap = fieldEnumDescriptorMap(fieldEnums);
  if (fieldEnums.length > 0) {
    sections.push(emitFieldEnumPrimitives(fieldEnums), "");
  }

  for (const contentType of selectedContentTypes) {
    if (flags.includeFlat) {
      sections.push(
        ...emitContentTypeSchema(contentType, {
          localization: "flat",
          config,
          fieldEnums: fieldEnumMap,
        })
      );
    }

    if (flags.includeLocalizedOnly) {
      sections.push(
        ...emitContentTypeSchema(contentType, {
          localization: "localized-only",
          config,
          fieldEnums: fieldEnumMap,
        }),
        ...emitContentTypeLocalizedEntrySchema(contentType)
      );
    }
  }

  if (selectedContentTypes.length > 0) {
    sections.push(
      "",
      emitContentTypeIdPrimitives(selectedContentTypes, {
        includeEntryMaps: flags.includeLocalizedOnly,
      })
    );
  }

  const helpers = emitLocaleHelpers(selectedContentTypes, flags, config);
  if (helpers) {
    sections.push("", helpers);
  }

  if (flags.includeLocalizedOnly && linkFieldTargets.length > 0) {
    const linkHelpers = emitLinkFieldParseHelpers(linkFieldTargets);
    if (linkHelpers) {
      sections.push("", linkHelpers);
    }
  }

  if (flags.includeLocalizedOnly && selectedContentTypes.length > 0) {
    sections.push("", emitLinkFieldMetadata(selectedContentTypes, linkFields));
  }

  return `${sections.join("\n").trimEnd()}\n`;
}
