import {
  defineConfig,
  resolveLocaleMode,
  type ContentfulToZodConfig,
  type LocaleMode,
} from "../config/define-config";
import type { ContentField, ContentType } from "../model/content-type";
import type { Locale } from "../model/locale";
import {
  deliveryFieldSource,
  fieldToZod,
  flatFieldSource,
  validateObjectOverrides,
  type FieldZodResult,
} from "./field-to-zod";
import { emitLocalePrimitives, requireLocalesForMode } from "./locale-primitives";
import { CONTENTFUL_PRIMITIVE_SCHEMA_NAMES, CONTENTFUL_PRIMITIVE_SCHEMAS } from "./primitives";
import {
  deliveryFieldsTypeName,
  deliverySchemaExportName,
  fieldsTypeName,
  schemaExportName,
} from "./schema-name";
import { emitLocaleHelpers } from "./helpers-to-source";
import { zodToSource } from "./zod-to-source";

export type { LocaleMode };

export interface GenerateZodSchemasOptions {
  contentTypeIds?: string[] | undefined;
  locales?: Locale[] | undefined;
  localeMode?: LocaleMode | undefined;
  config?: ContentfulToZodConfig | undefined;
}

function filterContentTypes(
  contentTypes: ContentType[],
  contentTypeIds: string[] | undefined
): ContentType[] {
  if (!contentTypeIds?.length) {
    return contentTypes;
  }

  const allowed = new Set(contentTypeIds);
  const filtered = contentTypes.filter((contentType) => allowed.has(contentType.id));

  for (const id of contentTypeIds) {
    if (!filtered.some((contentType) => contentType.id === id)) {
      throw new Error(`Content type "${id}" was not found in the provided snapshot.`);
    }
  }

  return filtered;
}

function fieldSource(flat: FieldZodResult, field: ContentField, delivery: boolean): string {
  if (!delivery) {
    return flatFieldSource(flat, field);
  }

  return deliveryFieldSource(flat, field);
}

function emitContentTypeSchema(
  contentType: ContentType,
  options: {
    delivery: boolean;
    config?: ContentfulToZodConfig | undefined;
  }
): string[] {
  const shapeEntries: string[] = [];

  for (const field of contentType.fields) {
    const flat = fieldToZod(field, {
      contentTypeId: contentType.id,
      config: options.config,
    });

    shapeEntries.push(
      `  ${JSON.stringify(field.id)}: ${fieldSource(flat, field, options.delivery)},`
    );
  }

  const exportName = options.delivery
    ? deliverySchemaExportName(contentType.id)
    : schemaExportName(contentType.id);
  const typeName = options.delivery
    ? deliveryFieldsTypeName(contentType.id)
    : fieldsTypeName(contentType.id);

  return [
    `export const ${exportName} = z.object({`,
    ...shapeEntries,
    "});",
    "",
    `export type ${typeName} = z.infer<typeof ${exportName}>;`,
    "",
  ];
}

function emitFileHeader(): string {
  return [
    "/**",
    " * @generated by @xndrjs/contentful-to-zod",
    " * Do not edit manually.",
    " */",
    "",
    'import { z } from "zod";',
    "",
  ].join("\n");
}

function emitSharedPrimitives(): string {
  const lines = CONTENTFUL_PRIMITIVE_SCHEMA_NAMES.flatMap((name) => {
    const schema = CONTENTFUL_PRIMITIVE_SCHEMAS[name];
    return [`export const ${name} = ${zodToSource(schema)};`, ""];
  });

  return lines.join("\n");
}

/** Generate a self-contained TypeScript module with Zod schemas for Contentful content types. */
export function generateZodSchemas(
  contentTypes: ContentType[],
  options: GenerateZodSchemasOptions = {}
): string {
  const config = options.config ? defineConfig(options.config) : undefined;
  const localeMode = resolveLocaleMode({ localeMode: options.localeMode, config });
  const locales = requireLocalesForMode(localeMode, options.locales);
  const selectedContentTypes = filterContentTypes(contentTypes, options.contentTypeIds);

  validateObjectOverrides(selectedContentTypes, config);

  const sections: string[] = [emitFileHeader()];

  const includeDelivery = localeMode === "delivery" || localeMode === "both";
  const includeCma = localeMode === "cma" || localeMode === "both";

  if (includeDelivery && locales) {
    sections.push(emitLocalePrimitives(locales), "");
  }

  sections.push(emitSharedPrimitives());

  for (const contentType of selectedContentTypes) {
    if (includeCma) {
      sections.push(
        ...emitContentTypeSchema(contentType, {
          delivery: false,
          config,
        })
      );
    }

    if (includeDelivery) {
      sections.push(
        ...emitContentTypeSchema(contentType, {
          delivery: true,
          config,
        })
      );
    }
  }

  const helpers = emitLocaleHelpers(selectedContentTypes, localeMode);
  if (helpers) {
    sections.push("", helpers);
  }

  return `${sections.join("\n").trimEnd()}\n`;
}
