/**
 * Datasource codegen: context types, createDataSources wiring, DSL vs impl when.
 */
import { describe, expect, it } from "vitest";

import { parseAndCheck } from "../../parse-and-check";
import { composeGeneratedModule } from "../compose-generated-module";
import { generateDataSources } from "../generators/generate-datasources";
import { emitDataSources } from "./emit-datasources";

const prelude = `
  scalar Locale on string;
  scalar EntryId on string;
  scalar AssetId on string;

  resource Entry(id: EntryId, locale: Locale): {
    id
    type: string
    locale
  }

  resource Asset(id: AssetId, locale: Locale): {
    id
    locale
  }
`;

const coveredQuery = `
  query Q(id: EntryId) {
    context { locale: Locale }
    root Entry(id: id, locale: context.locale)
    on Entry e { id type }
    on Asset a { id }
  }
`;

function checked(source: string) {
  const result = parseAndCheck(source);
  expect(result.diagnostics).toEqual([]);
  return result.program;
}

describe("emitDataSources", () => {
  it("returns empty string when no datasources are declared", () => {
    const program = checked(`
      ${prelude}
      ${coveredQuery}
    `);
    expect(emitDataSources(program)).toBe("");
    expect(generateDataSources(program).code).toBe(
      "/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */\n"
    );
  });

  it("emits context types, config shape, and defineDataSourceFor wiring (golden)", () => {
    const program = checked(`
      ${prelude}

      datasource CmsSource {
        context { locale: Locale }
        for Entry e when context.locale == @e.locale
        for Asset a
      }

      ${coveredQuery}
    `);

    const { code } = generateDataSources(program);

    expect(code).toContain("defineDataSourceFor");
    expect(code).toContain("type ResourceLoadContext");
    expect(code).not.toContain("SourceRouteContext");
    expect(code).toContain("batchSize: config.CmsSource.batchSize");
    expect(code).toContain("concurrency: config.CmsSource.concurrency");

    const golden = `
/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */

import { defineDataSourceFor, type DataSource, type ResourceLoadContext } from "@xndrjs/ziel";

export type CmsSourceContext = {
  locale: Locale;
};

export type ZielExecutionContext = {
  locale: Locale;
};

type CmsSourceConfig = {
  load: (
    batch: readonly (EntryResource | AssetResource)[],
    context: ResourceLoadContext<CmsSourceContext>
  ) => Promise<readonly (EntryPayload | AssetPayload | undefined)[]>;
  batchSize?: number;
  concurrency?: number;
};

export function createDataSources<C extends ZielExecutionContext>(
  config: {
    CmsSource: CmsSourceConfig;
  }
): DataSource<ContentRegistry, C>[] {
  const defineSource = defineDataSourceFor<ContentRegistry, C>();

  return [
    defineSource({
      id: "CmsSource",
      for: [entryAri, assetAri],
      batchSize: config.CmsSource.batchSize,
      concurrency: config.CmsSource.concurrency,
      when: ({ executionContext, resource }) => {
        if (entryAri.matches(resource)) {
          return executionContext.locale == resource.key[0].locale;
        }
        if (assetAri.matches(resource)) {
          return true;
        }
        return false;
      },
      load: (batch, ctx) =>
        config.CmsSource.load(batch as readonly (EntryResource | AssetResource)[], {
          ...ctx,
          executionContext: ctx.executionContext,
        }),
    })
  ];
}
`;

    expect(code.trim()).toBe(golden.trim());
  });

  it("includes optional config when when every route omits DSL when", () => {
    const program = checked(`
      ${prelude}

      datasource CmsSource {
        context { locale: Locale }
        for Entry
        for Asset
      }

      ${coveredQuery}
    `);

    const code = emitDataSources(program);

    expect(code).toContain("when?: (context: SourceRouteContext<CmsSourceContext>) => boolean;");
    expect(code).toContain("when: config.CmsSource.when,");
    expect(code).not.toContain("matches(resource)");

    const { code: moduleCode } = generateDataSources(program);
    expect(moduleCode).toContain("type SourceRouteContext");
  });

  it("omits config when when any route has a DSL when", () => {
    const program = checked(`
      ${prelude}

      datasource CmsSource {
        context { locale: Locale }
        for Entry e when context.locale == @e.locale
        for Asset
      }

      ${coveredQuery}
    `);

    const code = emitDataSources(program);

    expect(code).not.toContain("when?:");
    expect(code).toContain("when: ({ executionContext, resource }) => {");
    expect(code).toContain("entryAri.matches(resource)");
  });

  it("supports multiple datasources covering the same resource", () => {
    const program = checked(`
      ${prelude}

      datasource CmsSource {
        context { locale: Locale }
        for Entry e when context.locale == @e.locale
        for Asset
      }

      datasource PreviewSource {
        context { locale: Locale }
        for Entry e when @e.locale == context.locale
      }

      ${coveredQuery}
    `);

    const code = emitDataSources(program);

    expect(code).toContain("export type CmsSourceContext");
    expect(code).toContain("export type PreviewSourceContext");
    expect(code).toContain("CmsSource: CmsSourceConfig;");
    expect(code).toContain("PreviewSource: PreviewSourceConfig;");
    expect(code).toContain('id: "CmsSource"');
    expect(code).toContain('id: "PreviewSource"');
    expect(code).toContain("for: [entryAri, assetAri]");
    expect(code).toContain("for: [entryAri]");
  });

  it("merges aggregate ZielExecutionContext across datasources", () => {
    const program = checked(`
      scalar Locale on string;
      scalar EntryId on string;
      scalar ApiKey on string;

      resource Entry(id: EntryId, locale: Locale): {
        id
        locale
      }

      datasource CmsSource {
        context { locale: Locale }
        for Entry
      }

      datasource ApiSource {
        context {
          locale: Locale
          apiKey: ApiKey
        }
        for Entry
      }

      query Q(id: EntryId) {
        context {
          locale: Locale
          apiKey: ApiKey
        }
        root Entry(id: id, locale: context.locale)
        on Entry e { id }
      }
    `);

    const code = emitDataSources(program);

    expect(code).toContain(
      ["export type ZielExecutionContext = {", "  locale: Locale;", "  apiKey: ApiKey;", "};"].join(
        "\n"
      )
    );
  });

  it("wires into composeGeneratedModule with exact config keys", () => {
    const program = checked(`
      ${prelude}

      datasource CmsSource {
        context { locale: Locale }
        for Entry
        for Asset
      }

      ${coveredQuery}
    `);

    const { code } = composeGeneratedModule(program);

    expect(code).toContain("export function createDataSources");
    expect(code).toContain("defineDataSourceFor");
    expect(code).toContain("type ResourceLoadContext");
    expect(code).toContain("type SourceRouteContext");
    expect(code).toContain("CmsSource: CmsSourceConfig");
    expect(code).toContain("export const entryAri");
    expect(code).toContain("export type ContentRegistry");
  });
});
