/**
 * Datasource codegen: context types, per-query create*DataSources, DSL vs impl when.
 */
import { describe, expect, it } from "vitest";

import { parseAndCheck } from "../../parse-and-check";
import { composeGeneratedModules } from "../compose-generated-module";
import { generateDataSources } from "../generators/generate-datasources";
import { emitDataSources } from "./emit-datasources";

const prelude = `
  scalar Locale on string;
  scalar EntryId on string;
  scalar AssetId on string;

  resource Entry(id: EntryId, locale: Locale): {
    id
    type: string
    locale
  }

  resource Asset(id: AssetId, locale: Locale): {
    id
    locale
  }
`;

const coveredQuery = `
  query Q(id: EntryId, locale: Locale) {
    context {
    locale
  }
    root Entry(id: id, locale: locale)
    on Entry e { id type }
    on Asset a { id }
  }
`;

function checked(source: string) {
  const result = parseAndCheck(source);
  expect(result.diagnostics).toEqual([]);
  return result.program;
}

describe("emitDataSources", () => {
  it("returns empty string when no datasources are declared", () => {
    const program = checked(`
      ${prelude}
      ${coveredQuery}
    `);
    expect(emitDataSources(program)).toBe("");
    expect(generateDataSources(program).code).toBe(
      "/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */\n"
    );
  });

  it("emits context types, config shape, and per-query defineDataSourceFor wiring (golden)", () => {
    const program = checked(`
      ${prelude}

      datasource CmsSource {
        context { locale: Locale }
        for Entry e when context.locale == @e.locale
        for Asset a
      }

      ${coveredQuery}
    `);

    const { code } = generateDataSources(program);

    expect(code).toContain("defineDataSourceFor");
    expect(code).toContain("type ResourceLoadContext");
    expect(code).not.toContain("SourceRouteContext");
    expect(code).toContain("batchSize: config.CmsSource.batchSize");
    expect(code).toContain("concurrency: config.CmsSource.concurrency");
    expect(code).toContain("export function createQDataSources");
    expect(code).not.toContain("export function createDataSources");

    const golden = `
/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */

import { defineDataSourceFor, type DataSource, type ResourceLoadContext } from "@xndrjs/ziel";

export type CmsSourceContext = {
  locale: Locale;
};

export type ZielExecutionContext = {
  locale: Locale;
};

export type CmsSourceConfig = {
  load: (
    batch: readonly (EntryResource | AssetResource)[],
    context: ResourceLoadContext<CmsSourceContext>
  ) => Promise<readonly (EntryPayload | AssetPayload | undefined)[]>;
  batchSize?: number;
  concurrency?: number;
};

export type QExecutionContext = {
  locale: Locale;
};

export function createQDataSources(
  config: {
    CmsSource: CmsSourceConfig;
  }
): DataSource<ContentRegistry, QExecutionContext>[] {
  const defineSource = defineDataSourceFor<ContentRegistry, QExecutionContext>();

  return [
    defineSource({
      id: "CmsSource",
      for: [entryAri, assetAri],
      batchSize: config.CmsSource.batchSize,
      concurrency: config.CmsSource.concurrency,
      when: ({ executionContext, resource }) => {
        if (entryAri.matches(resource)) {
          return executionContext.locale == resource.key.locale;
        }
        if (assetAri.matches(resource)) {
          return true;
        }
        return false;
      },
      load: (batch, ctx) =>
        config.CmsSource.load(batch as readonly (EntryResource | AssetResource)[], {
          ...ctx,
          executionContext: ctx.executionContext,
        }),
    })
  ];
}
`;

    expect(code.trim()).toBe(golden.trim());
  });

  it("includes optional config when when every route omits DSL when", () => {
    const program = checked(`
      ${prelude}

      datasource CmsSource {
        context { locale: Locale }
        for Entry
        for Asset
      }

      ${coveredQuery}
    `);

    const code = emitDataSources(program);

    expect(code).toContain("when?: (context: SourceRouteContext<CmsSourceContext>) => boolean;");
    expect(code).toContain("when: config.CmsSource.when,");
    expect(code).not.toContain("matches(resource)");

    const { code: moduleCode } = generateDataSources(program);
    expect(moduleCode).toContain("type SourceRouteContext");
  });

  it("uses unknown consistently for empty datasource and query contexts", () => {
    const program = checked(`
      scalar Id on string;
      resource Item(id: Id): { id }

      datasource InMemory {
        context { }
        for Item
      }

      query Q(id: Id) {
        context { }
        root Item(id: id)
        on Item item { id }
      }
    `);

    const code = emitDataSources(program);

    expect(code).toContain("export type InMemoryContext = unknown;");
    expect(code).toContain("export type ZielExecutionContext = unknown;");
    expect(code).toContain("ResourceLoadContext<InMemoryContext>");
    expect(code).toContain("SourceRouteContext<InMemoryContext>");
    expect(code).toContain("DataSource<ContentRegistry, unknown>[]");
    expect(code).toContain("defineDataSourceFor<ContentRegistry, unknown>()");
  });

  it("omits config when when any route has a DSL when", () => {
    const program = checked(`
      ${prelude}

      datasource CmsSource {
        context { locale: Locale }
        for Entry e when context.locale == @e.locale
        for Asset
      }

      ${coveredQuery}
    `);

    const code = emitDataSources(program);

    expect(code).not.toContain("when?:");
    expect(code).toContain("when: ({ executionContext, resource }) => {");
    expect(code).toContain("entryAri.matches(resource)");
  });

  it("supports multiple datasources covering the same resource", () => {
    const program = checked(`
      ${prelude}

      datasource CmsSource {
        context { locale: Locale }
        for Entry e when context.locale == @e.locale
        for Asset
      }

      datasource PreviewSource {
        context { locale: Locale }
        for Entry e when @e.locale == context.locale
      }

      ${coveredQuery}
    `);

    const code = emitDataSources(program);

    expect(code).toContain("export type CmsSourceContext");
    expect(code).toContain("export type PreviewSourceContext");
    expect(code).toContain("CmsSource: CmsSourceConfig;");
    expect(code).toContain("PreviewSource: PreviewSourceConfig;");
    expect(code).toContain('id: "CmsSource"');
    expect(code).toContain('id: "PreviewSource"');
    expect(code).toContain("for: [entryAri, assetAri]");
    expect(code).toContain("for: [entryAri]");
  });

  it("merges aggregate ZielExecutionContext across datasources", () => {
    const program = checked(`
      scalar Locale on string;
      scalar EntryId on string;
      scalar ApiKey on string;

      resource Entry(id: EntryId, locale: Locale): {
        id
        locale
      }

      datasource CmsSource {
        context { locale: Locale }
        for Entry
      }

      datasource ApiSource {
        context {
          locale: Locale
          apiKey: ApiKey
        }
        for Entry
      }

      query Q(id: EntryId, locale: Locale, apiKey: ApiKey) {
        context {
    locale
    apiKey
  }
        root Entry(id: id, locale: locale)
        on Entry e { id }
      }
    `);

    const code = emitDataSources(program);

    expect(code).toContain(
      ["export type ZielExecutionContext = {", "  locale: Locale;", "  apiKey: ApiKey;", "};"].join(
        "\n"
      )
    );
  });

  it("emits one factory per query with only intersecting datasources", () => {
    const program = checked(`
      scalar Locale on string;
      scalar EntryId on string;
      scalar AssetId on string;
      scalar Sku on string;

      resource Entry(id: EntryId, locale: Locale): {
        id
        locale
      }

      resource Asset(id: AssetId, locale: Locale): {
        id
        locale
      }

      resource Product(sku: Sku): {
        sku
        title: string
      }

      datasource CmsSource {
        context { locale: Locale }
        for Entry
        for Asset
      }

      datasource CatalogApi {
        context { locale: Locale }
        for Product
      }

      query PageDetail(id: EntryId, locale: Locale) {
        context {
    locale
  }
        root Entry(id: id, locale: locale)
        on Entry e { id }
        on Asset a { id }
      }

      query ProductDetail(sku: Sku, locale: Locale) {
        context {
    locale
  }
        root Product(sku: sku)
        on Product p { sku title }
      }
    `);

    const code = emitDataSources(program);

    expect(code).toContain("export function createPageDetailDataSources");
    expect(code).toContain("export function createProductDetailDataSources");
    expect(code).not.toContain("export function createDataSources");

    const pageFactory = code.slice(
      code.indexOf("export function createPageDetailDataSources"),
      code.indexOf("export function createProductDetailDataSources")
    );
    expect(pageFactory).toContain("CmsSource: CmsSourceConfig");
    expect(pageFactory).not.toContain("CatalogApi");
    expect(pageFactory).toContain("DataSource<ContentRegistry, PageDetailExecutionContext>");

    const productFactory = code.slice(
      code.indexOf("export function createProductDetailDataSources")
    );
    expect(productFactory).toContain("CatalogApi: CatalogApiConfig");
    expect(productFactory).not.toContain("CmsSource");
    expect(productFactory).toContain("DataSource<ContentRegistry, ProductDetailExecutionContext>");
  });

  it("wires into composeGeneratedModules with exact config keys", () => {
    const program = checked(`
      ${prelude}

      datasource CmsSource {
        context { locale: Locale }
        for Entry
        for Asset
      }

      ${coveredQuery}
    `);

    const { files } = composeGeneratedModules(program);
    const resources = files.find((f) => f.relativePath === "resources.ts")!;
    const query = files.find((f) => f.relativePath === "Q.query.ts")!;

    expect(query.code).toContain("export function createQDataSources");
    expect(query.code).not.toContain("export function createDataSources");
    expect(query.code).toContain("defineDataSourceFor");
    expect(resources.code).toContain("type ResourceLoadContext");
    expect(resources.code).toContain("type SourceRouteContext");
    expect(query.code).toContain("CmsSource: CmsSourceConfig");
    expect(resources.code).toContain("export const entryAri");
    expect(resources.code).toContain("export type ContentRegistry");
    // Query module emits ExecutionContext (from strategies) before the factory.
    expect(query.code.indexOf("export type QExecutionContext")).toBeLessThan(
      query.code.indexOf("export function createQDataSources")
    );
  });
});
