/**
 * Merge resource + strategy + projection + resolve façade codegen into one
 * TypeScript module for the product path (`buildResources` / CLI). Keeps
 * `generateResources` / `generateStrategies` / `generateProjections` as focused
 * unit-test entry points with separate imports.
 */
import type { Program } from "../../ir";
import { emitProjectionTypes } from "./emitters/emit-projection-types";
import { emitProjections } from "./emitters/emit-projections";
import { emitResolves } from "./emitters/emit-resolves";
import { emitPayloadTypes } from "./emitters/emit-types";
import { emitRegistry } from "./emitters/emit-registry";
import { emitResources } from "./emitters/emit-resources";
import { emitScalars } from "./emitters/emit-scalars";
import { emitStrategies } from "./emitters/emit-strategies";
import type { GenerateResourcesOptions } from "./generators/generate-resources";

const GENERATED_HEADER = "/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */";

const DEFAULT_IMPORT_FROM = "@xndrjs/naviql";
const DEFAULT_REGISTRY_TYPE_NAME = "ContentRegistry";

export type ComposeGeneratedModuleOptions = GenerateResourcesOptions;

export type ComposeGeneratedModuleResult = {
  /** Full TypeScript module source. */
  code: string;
};

type ResolvedOptions = {
  importFrom: string;
  registryTypeName: string;
};

function resolveOptions(options?: ComposeGeneratedModuleOptions): ResolvedOptions {
  return {
    importFrom: options?.importFrom ?? DEFAULT_IMPORT_FROM,
    registryTypeName: options?.registryTypeName ?? DEFAULT_REGISTRY_TYPE_NAME,
  };
}

function emitRuntimeImport(importFrom: string, symbols: string[]): string {
  return `import { ${symbols.join(", ")} } from ${JSON.stringify(importFrom)};`;
}

/**
 * Compose a single generated module: scalars / ARIs / payloads / registry,
 * plus open strategy builders, projectors, and resolve façades when the program
 * has queries.
 *
 * Uses one header and one runtime import (`ari`, `s`,
 * `createGraphResolutionStrategy`, `createResourceGraphResolver`, and related
 * types as needed).
 */
export function composeGeneratedModule(
  program: Program,
  options?: ComposeGeneratedModuleOptions
): ComposeGeneratedModuleResult {
  const { importFrom, registryTypeName } = resolveOptions(options);

  const bodyParts: string[] = [];

  const scalars = emitScalars(program);
  if (scalars.length > 0) {
    bodyParts.push(scalars);
  }

  const resources = emitResources(program);
  if (resources.length > 0) {
    bodyParts.push(resources);
  }

  const payloadTypes = emitPayloadTypes(program);
  if (payloadTypes.length > 0) {
    bodyParts.push(payloadTypes);
  }

  const registry = emitRegistry(program, registryTypeName);
  if (registry.length > 0) {
    bodyParts.push(registry);
  }

  const strategies = emitStrategies(program, registryTypeName);
  if (strategies.length > 0) {
    bodyParts.push(strategies);
  }

  const projectionTypes = emitProjectionTypes(program);
  if (projectionTypes.length > 0) {
    bodyParts.push(projectionTypes);
  }

  const projections = emitProjections(program, registryTypeName);
  if (projections.length > 0) {
    bodyParts.push(projections);
  }

  const resolves = emitResolves(program, registryTypeName);
  if (resolves.length > 0) {
    bodyParts.push(resolves);
  }

  const importSymbols: string[] = [];
  if (resources.length > 0) {
    importSymbols.push("ari", "s");
  }

  if (strategies.length > 0) {
    importSymbols.push("createGraphResolutionStrategy");
  }

  if (projections.length > 0) {
    importSymbols.push("type ContentMap");
    if (program.queries.some((q) => q.projections.some((p) => p.resolveArms !== null))) {
      importSymbols.push("type ApplicationResourceIdentifier", "type ResourceKey");
    }
  }

  if (resolves.length > 0) {
    for (const symbol of [
      "createResourceGraphResolver",
      "type DataSource",
      "type IslandDependencyMap",
      "type IslandMap",
      "type MissingResourceMode",
      "type ResolutionError",
      "type ResolutionObserver",
      "type ResourceKey",
      "type SchedulingMode",
    ]) {
      if (!importSymbols.includes(symbol)) {
        importSymbols.push(symbol);
      }
    }
  }

  const parts: string[] = [GENERATED_HEADER];

  if (importSymbols.length > 0) {
    parts.push(emitRuntimeImport(importFrom, importSymbols));
  }

  parts.push(...bodyParts);

  return { code: `${parts.join("\n\n")}\n` };
}
