/**
 * Merge resource + strategy codegen into one TypeScript module for the product
 * path (`buildResources` / CLI). Keeps `generateResources` / `generateStrategies`
 * as focused unit-test entry points with separate imports.
 */
import type { Program } from "../../ir";
import { emitPayloadTypes } from "./emit-types";
import { emitRegistry } from "./emit-registry";
import { emitResources } from "./emit-resources";
import { emitScalars } from "./emit-scalars";
import { emitStrategies } from "./emit-strategies";
import type { GenerateResourcesOptions } from "./generate-resources";

const GENERATED_HEADER = "/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */";

const DEFAULT_IMPORT_FROM = "@xndrjs/naviql";
const DEFAULT_REGISTRY_TYPE_NAME = "ContentRegistry";

export type ComposeGeneratedModuleOptions = GenerateResourcesOptions;

export type ComposeGeneratedModuleResult = {
  /** Full TypeScript module source. */
  code: string;
};

type ResolvedOptions = {
  importFrom: string;
  registryTypeName: string;
};

function resolveOptions(options?: ComposeGeneratedModuleOptions): ResolvedOptions {
  return {
    importFrom: options?.importFrom ?? DEFAULT_IMPORT_FROM,
    registryTypeName: options?.registryTypeName ?? DEFAULT_REGISTRY_TYPE_NAME,
  };
}

function emitRuntimeImport(importFrom: string, symbols: string[]): string {
  return `import { ${symbols.join(", ")} } from ${JSON.stringify(importFrom)};`;
}

/**
 * Compose a single generated module: scalars / ARIs / payloads / registry,
 * plus open strategy builders when the program has queries.
 *
 * Uses one header and one runtime import (`ari`, `s`, and/or
 * `createGraphResolutionStrategy` as needed).
 */
export function composeGeneratedModule(
  program: Program,
  options?: ComposeGeneratedModuleOptions
): ComposeGeneratedModuleResult {
  const { importFrom, registryTypeName } = resolveOptions(options);

  const bodyParts: string[] = [];

  const scalars = emitScalars(program);
  if (scalars.length > 0) {
    bodyParts.push(scalars);
  }

  const resources = emitResources(program);
  if (resources.length > 0) {
    bodyParts.push(resources);
  }

  const payloadTypes = emitPayloadTypes(program);
  if (payloadTypes.length > 0) {
    bodyParts.push(payloadTypes);
  }

  const registry = emitRegistry(program, registryTypeName);
  if (registry.length > 0) {
    bodyParts.push(registry);
  }

  const strategies = emitStrategies(program, registryTypeName);
  if (strategies.length > 0) {
    bodyParts.push(strategies);
  }

  const importSymbols: string[] = [];
  if (resources.length > 0) {
    importSymbols.push("ari", "s");
  }

  if (strategies.length > 0) {
    importSymbols.push("createGraphResolutionStrategy");
  }

  const parts: string[] = [GENERATED_HEADER];

  if (importSymbols.length > 0) {
    parts.push(emitRuntimeImport(importFrom, importSymbols));
  }

  parts.push(...bodyParts);

  return { code: `${parts.join("\n\n")}\n` };
}
