/**
 * Resource codegen entry: checked `Program` → TypeScript source string.
 * Emits branded scalars, ARI factories, payload types, and a registry slice.
 * Queries are ignored. Generated code imports runtime only from `@xndrjs/naviql`.
 */
import type { Program } from "../../ir";
import { emitPayloadTypes } from "./emit-types";
import { emitRegistry } from "./emit-registry";
import { emitResources } from "./emit-resources";
import { emitScalars } from "./emit-scalars";

const GENERATED_HEADER = "/* Generated by @xndrjs/naviql/compile. Do not edit by hand. */";

const DEFAULT_IMPORT_FROM = "@xndrjs/naviql";
const DEFAULT_REGISTRY_TYPE_NAME = "ContentRegistry";

export type GenerateResourcesOptions = {
  /** Module specifier for `ari` / `s` imports. Default: `@xndrjs/naviql`. */
  importFrom?: string;
  /** Name of the emitted registry type. Default: `ContentRegistry`. */
  registryTypeName?: string;
};

export type GenerateResourcesResult = {
  /** Full TypeScript module source. */
  code: string;
};

type ResolvedOptions = {
  importFrom: string;
  registryTypeName: string;
};

function resolveOptions(options?: GenerateResourcesOptions): ResolvedOptions {
  return {
    importFrom: options?.importFrom ?? DEFAULT_IMPORT_FROM,
    registryTypeName: options?.registryTypeName ?? DEFAULT_REGISTRY_TYPE_NAME,
  };
}

function emitRuntimeImport(importFrom: string): string {
  return `import { ari, s } from ${JSON.stringify(importFrom)};`;
}

/**
 * Generate TypeScript source for resource definitions in `program`.
 *
 * Input should already be checked (`checkProgram` / `parseAndCheck`).
 * Queries are ignored. Output is a pure string (no filesystem writes).
 */
export function generateResources(
  program: Program,
  options?: GenerateResourcesOptions
): GenerateResourcesResult {
  const { importFrom, registryTypeName } = resolveOptions(options);

  const bodyParts: string[] = [];

  const scalars = emitScalars(program);
  if (scalars.length > 0) {
    bodyParts.push(scalars);
  }

  const resources = emitResources(program);
  if (resources.length > 0) {
    bodyParts.push(resources);
  }

  const payloadTypes = emitPayloadTypes(program);
  if (payloadTypes.length > 0) {
    bodyParts.push(payloadTypes);
  }

  const registry = emitRegistry(program, registryTypeName);
  if (registry.length > 0) {
    bodyParts.push(registry);
  }

  const parts: string[] = [GENERATED_HEADER];

  // Import only when a section that may reference `ari` / `s` is present.
  if (resources.length > 0) {
    parts.push(emitRuntimeImport(importFrom));
  }

  parts.push(...bodyParts);

  return { code: `${parts.join("\n\n")}\n` };
}
