/**
 * Merge resource + datasource + strategy + projection + resolve façade codegen
 * into generated TypeScript modules for the product path
 * (`buildGeneratedModule` / CLI).
 *
 * Product emit is multi-file: `resources.ts`, one `{kebab}.query.ts` per query,
 * and a barrel `index.ts`. Keeps `generateResources` / `generateStrategies` /
 * `generateProjections` / `generateDataSources` as focused unit-test entry
 * points with separate imports.
 */
import type { QueryPlan } from "../../analyze";
import type { ProgramAnalysis } from "../../check";
import type { Program } from "../../ir";
import {
  datasourcesNeedSourceRouteContext,
  emitDataSourceTypes,
  emitQueryDataSourcesFactory,
} from "./datasources";
import type { GenerateResourcesOptions } from "./generators/generate-resources";
import { resolveQueryModulePaths } from "./naming";
import { emitQueryProjection, emitQueryProjectionTypes } from "./projections";
import {
  emitOpaques,
  emitPayloadTypes,
  emitRegistry,
  emitResources,
  emitScalars,
} from "./resources";
import { emitQueryResolve } from "./resolve-facades";
import { emitQueryStrategy } from "./strategies";
import { codegenAnalysis } from "./analysis";

/** Header stamped on every managed multi-file emit (`resources.ts`, `*.query.ts`, `index.ts`). */
export const GENERATED_MODULE_HEADER =
  "/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */";

const DEFAULT_IMPORT_FROM = "@xndrjs/ziel";
const DEFAULT_REGISTRY_TYPE_NAME = "ContentRegistry";

export const RESOURCES_FILE = "resources.ts";
export const INDEX_FILE = "index.ts";
const RESOURCES_IMPORT_FROM = "./resources";

/**
 * True when a flat path under `out` is a Ziel-managed codegen artifact: known
 * basename (`resources.ts`, `index.ts`, or `*.query.ts`) that still carries
 * {@link GENERATED_MODULE_HEADER}. Used by the CLI to delete stale outputs only.
 */
export function isManagedGeneratedOutput(relativePath: string, content: string): boolean {
  if (relativePath.includes("/") || relativePath.includes("\\")) return false;
  const managedName =
    relativePath === RESOURCES_FILE ||
    relativePath === INDEX_FILE ||
    relativePath.endsWith(".query.ts");
  if (!managedName) return false;
  return content.includes(GENERATED_MODULE_HEADER);
}

export type ComposeGeneratedModuleOptions = GenerateResourcesOptions & {
  /**
   * Optional property name stamped with the resource name on projection shells
   * and types (e.g. `"$type"` or `"__resource"`). Default: unset (no stamp).
   */
  resourceTag?: string;
};

export type ComposeGeneratedModuleResult = {
  /** Full TypeScript module source (legacy single-module compose). */
  code: string;
};

export type GeneratedModuleFile = {
  /** Path relative to the configured `out` directory. */
  relativePath: string;
  /** Full TypeScript module source. */
  code: string;
};

export type ComposeGeneratedModulesResult = {
  files: GeneratedModuleFile[];
};

type ResolvedOptions = {
  importFrom: string;
  registryTypeName: string;
  resourceTag: string | undefined;
};

type ExportedSymbol = {
  name: string;
  /** True when the symbol is only a type alias (import with `type`). */
  typeOnly: boolean;
};

function resolveOptions(options?: ComposeGeneratedModuleOptions): ResolvedOptions {
  return {
    importFrom: options?.importFrom ?? DEFAULT_IMPORT_FROM,
    registryTypeName: options?.registryTypeName ?? DEFAULT_REGISTRY_TYPE_NAME,
    resourceTag: options?.resourceTag,
  };
}

function emitRuntimeImport(importFrom: string, symbols: string[]): string {
  return `import { ${symbols.join(", ")} } from ${JSON.stringify(importFrom)};`;
}

function emitLocalImport(from: string, symbols: string[]): string {
  return `import { ${symbols.join(", ")} } from ${JSON.stringify(from)};`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** True when `code` references `symbol` as a TypeScript identifier ( `_` is part of names). */
function codeReferencesSymbol(code: string, symbol: string): boolean {
  const re = new RegExp(`(?:^|[^A-Za-z0-9_])${escapeRegExp(symbol)}(?:[^A-Za-z0-9_]|$)`);
  return re.test(code);
}

function collectExportedSymbols(code: string): ExportedSymbol[] {
  const byName = new Map<string, ExportedSymbol>();

  for (const match of code.matchAll(/^export type (\w+)\b/gm)) {
    const name = match[1]!;
    const existing = byName.get(name);
    if (existing === undefined) {
      byName.set(name, { name, typeOnly: true });
    }
  }

  for (const match of code.matchAll(/^export (?:const|function|async function) (\w+)\b/gm)) {
    const name = match[1]!;
    byName.set(name, { name, typeOnly: false });
  }

  return [...byName.values()];
}

function selectReferencedImports(code: string, exports: readonly ExportedSymbol[]): string[] {
  const symbols: string[] = [];
  for (const exported of exports) {
    if (!codeReferencesSymbol(code, exported.name)) {
      continue;
    }
    symbols.push(exported.typeOnly ? `type ${exported.name}` : exported.name);
  }
  return symbols;
}

function pushUnique(symbols: string[], symbol: string): void {
  if (!symbols.includes(symbol)) {
    symbols.push(symbol);
  }
}

function resourcesRuntimeImports(program: Program): string[] {
  const importSymbols: string[] = [];
  if (emitResources(program).length > 0) {
    importSymbols.push("ari", "s");
  }
  if (emitOpaques(program).length > 0) {
    importSymbols.push("defineOpaqueType", "type OpaqueValueOf");
  }
  if (program.datasources.length > 0) {
    pushUnique(importSymbols, "type ResourceLoadContext");
    if (datasourcesNeedSourceRouteContext(program)) {
      pushUnique(importSymbols, "type SourceRouteContext");
    }
  }
  return importSymbols;
}

function queryRuntimeImports(
  plan: QueryPlan,
  body: string,
  hasDataSourcesFactory: boolean
): string[] {
  const importSymbols: string[] = [];

  pushUnique(importSymbols, "createGraphResolutionStrategy");
  if (body.includes("AddressableResourceIdentifier")) {
    pushUnique(importSymbols, "type AddressableResourceIdentifier");
  }
  if (body.includes("stricterOnFailure")) {
    pushUnique(importSymbols, "stricterOnFailure");
  }

  pushUnique(importSymbols, "type ContentMap");
  if (!importSymbols.includes("type AddressableResourceIdentifier")) {
    pushUnique(importSymbols, "type AddressableResourceIdentifier");
  }
  if (plan.hasRedirects) {
    pushUnique(importSymbols, "type ResourceKey");
  }
  if (plan.needsFailureProjection) {
    pushUnique(importSymbols, "type ResourceKey");
    if (
      !importSymbols.includes("type ResolutionError") &&
      !importSymbols.includes("ResolutionError")
    ) {
      pushUnique(importSymbols, "type ResolutionError");
    }
    pushUnique(importSymbols, "toResolutionErrorData");
  }
  if (plan.usesSetError) {
    pushUnique(importSymbols, "type ResolutionErrorData");
  }

  if (hasDataSourcesFactory) {
    pushUnique(importSymbols, "defineDataSourceFor");
    pushUnique(importSymbols, "type DataSource");
  }

  for (const symbol of [
    "createResourceGraphResolver",
    "type DataSource",
    "type IslandDependencyMap",
    "type IslandMap",
    "type ResolutionError",
    "type ResolutionBudgetOptions",
    "type ResolutionObserver",
    "type ResourceKey",
    "type SchedulingMode",
  ]) {
    if (symbol === "type ResolutionError" && importSymbols.includes("ResolutionError")) {
      continue;
    }
    pushUnique(importSymbols, symbol);
  }

  return importSymbols;
}

function assembleModule(importLines: string[], bodyParts: string[]): string {
  const parts: string[] = [
    GENERATED_MODULE_HEADER,
    ...importLines,
    ...bodyParts.filter((p) => p.length > 0),
  ];
  return `${parts.join("\n\n")}\n`;
}

function composeResourcesModule(program: Program, options: ResolvedOptions): string {
  const { importFrom, registryTypeName } = options;
  const bodyParts: string[] = [];

  const scalars = emitScalars(program);
  if (scalars.length > 0) {
    bodyParts.push(scalars);
  }

  const opaques = emitOpaques(program);
  if (opaques.length > 0) {
    bodyParts.push(opaques);
  }

  const resources = emitResources(program);
  if (resources.length > 0) {
    bodyParts.push(resources);
  }

  const payloadTypes = emitPayloadTypes(program);
  if (payloadTypes.length > 0) {
    bodyParts.push(payloadTypes);
  }

  const registry = emitRegistry(program, registryTypeName);
  if (registry.length > 0) {
    bodyParts.push(registry);
  }

  const datasourceTypes = emitDataSourceTypes(program);
  if (datasourceTypes.length > 0) {
    bodyParts.push(datasourceTypes);
  }

  const importSymbols = resourcesRuntimeImports(program);
  const importLines =
    importSymbols.length > 0 ? [emitRuntimeImport(importFrom, importSymbols)] : [];

  return assembleModule(importLines, bodyParts);
}

function composeQueryModule(
  plan: QueryPlan,
  analysis: ProgramAnalysis,
  resourcesExports: readonly ExportedSymbol[],
  options: ResolvedOptions
): string {
  const { importFrom, registryTypeName, resourceTag } = options;
  const program = analysis.program;
  const query = plan.query;
  const bodyParts: string[] = [];

  bodyParts.push(emitQueryStrategy(plan, registryTypeName));

  const hasDataSourcesFactory = program.datasources.length > 0;
  if (hasDataSourcesFactory) {
    bodyParts.push(emitQueryDataSourcesFactory(query, program.datasources, registryTypeName));
  }

  bodyParts.push(
    emitQueryProjectionTypes(
      plan,
      analysis.scalars,
      analysis.resources,
      analysis.opaques,
      resourceTag
    )
  );
  bodyParts.push(emitQueryProjection(plan, analysis.resources, registryTypeName, resourceTag));
  bodyParts.push(emitQueryResolve(plan, registryTypeName));

  const body = bodyParts.filter((p) => p.length > 0).join("\n\n");
  const runtimeSymbols = queryRuntimeImports(plan, body, hasDataSourcesFactory);
  const resourceSymbols = selectReferencedImports(body, resourcesExports);
  const importLines: string[] = [];
  if (runtimeSymbols.length > 0) {
    importLines.push(emitRuntimeImport(importFrom, runtimeSymbols));
  }
  if (resourceSymbols.length > 0) {
    importLines.push(emitLocalImport(RESOURCES_IMPORT_FROM, resourceSymbols));
  }

  return assembleModule(importLines, bodyParts);
}

function composeIndexModule(queryPaths: readonly string[]): string {
  const lines = [
    GENERATED_MODULE_HEADER,
    "",
    `export * from "./resources";`,
    ...queryPaths.map((path) => {
      const specifier = `./${path.replace(/\.ts$/, "")}`;
      return `export * from ${JSON.stringify(specifier)};`;
    }),
    "",
  ];
  return lines.join("\n");
}

/**
 * Compose the multi-file codegen product: shared `resources.ts`, one
 * `{kebab-query}.query.ts` per query, and a barrel `index.ts`.
 *
 * Query files import runtime from `importFrom` and shared symbols from
 * `./resources`. There are no cross-query imports.
 */
export function composeGeneratedModules(
  input: Program | ProgramAnalysis,
  options?: ComposeGeneratedModuleOptions
): ComposeGeneratedModulesResult {
  const analysis = codegenAnalysis(input);
  const program = analysis.program;
  const resolved = resolveOptions(options);

  const queryPaths = resolveQueryModulePaths(analysis.queries.map((q) => q.query.name));

  const resourcesCode = composeResourcesModule(program, resolved);
  const resourcesExports = collectExportedSymbols(resourcesCode);

  const files: GeneratedModuleFile[] = [{ relativePath: RESOURCES_FILE, code: resourcesCode }];

  for (const plan of analysis.queries) {
    const relativePath = queryPaths.get(plan.query.name)!;
    files.push({
      relativePath,
      code: composeQueryModule(plan, analysis, resourcesExports, resolved),
    });
  }

  files.push({
    relativePath: INDEX_FILE,
    code: composeIndexModule([...queryPaths.values()]),
  });

  return { files };
}

/**
 * Compose a single generated module: scalars / opaques / ARIs / payloads /
 * registry, plus per-query `create*DataSources` when datasources are declared,
 * and open strategy builders, projectors, and resolve façades when the program
 * has queries.
 *
 * Uses one header and one runtime import (`ari`, `s`, `defineOpaqueType`,
 * `OpaqueValueOf`, `createGraphResolutionStrategy`, `defineDataSourceFor`,
 * `createResourceGraphResolver`, and related types as needed).
 *
 * Section order: scalars → opaques → ARI/resources → payload → ContentRegistry
 * → datasource / strategy / projection / resolve.
 *
 * @deprecated Prefer {@link composeGeneratedModules} for the product path.
 */
export function composeGeneratedModule(
  input: Program | ProgramAnalysis,
  options?: ComposeGeneratedModuleOptions
): ComposeGeneratedModuleResult {
  const analysis = codegenAnalysis(input);
  const program = analysis.program;
  const { importFrom, registryTypeName, resourceTag } = resolveOptions(options);

  const bodyParts: string[] = [];

  const scalars = emitScalars(program);
  if (scalars.length > 0) {
    bodyParts.push(scalars);
  }

  const opaques = emitOpaques(program);
  if (opaques.length > 0) {
    bodyParts.push(opaques);
  }

  const resources = emitResources(program);
  if (resources.length > 0) {
    bodyParts.push(resources);
  }

  const payloadTypes = emitPayloadTypes(program);
  if (payloadTypes.length > 0) {
    bodyParts.push(payloadTypes);
  }

  const registry = emitRegistry(program, registryTypeName);
  if (registry.length > 0) {
    bodyParts.push(registry);
  }

  const datasourceTypes = emitDataSourceTypes(program);
  if (datasourceTypes.length > 0) {
    bodyParts.push(datasourceTypes);
  }

  // Strategies before datasource factories so `{Query}ExecutionContext` exists.
  const strategyParts: string[] = [];
  for (const plan of analysis.queries) {
    strategyParts.push(emitQueryStrategy(plan, registryTypeName));
  }
  const strategies = strategyParts.join("\n\n");
  if (strategies.length > 0) {
    bodyParts.push(strategies);
  }

  if (program.datasources.length > 0 && program.queries.length > 0) {
    const factories = program.queries
      .map((query) => emitQueryDataSourcesFactory(query, program.datasources, registryTypeName))
      .join("\n\n");
    if (factories.length > 0) {
      bodyParts.push(factories);
    }
  }

  const projectionTypeParts: string[] = [];
  const projectionParts: string[] = [];
  const resolveParts: string[] = [];
  for (const plan of analysis.queries) {
    projectionTypeParts.push(
      emitQueryProjectionTypes(
        plan,
        analysis.scalars,
        analysis.resources,
        analysis.opaques,
        resourceTag
      )
    );
    projectionParts.push(
      emitQueryProjection(plan, analysis.resources, registryTypeName, resourceTag)
    );
    resolveParts.push(emitQueryResolve(plan, registryTypeName));
  }
  const projectionTypes = projectionTypeParts.join("\n\n");
  if (projectionTypes.length > 0) {
    bodyParts.push(projectionTypes);
  }
  const projections = projectionParts.join("\n\n");
  if (projections.length > 0) {
    bodyParts.push(projections);
  }
  const resolves = resolveParts.join("\n\n");
  if (resolves.length > 0) {
    bodyParts.push(resolves);
  }

  const importSymbols: string[] = [];
  if (resources.length > 0) {
    importSymbols.push("ari", "s");
  }
  if (opaques.length > 0) {
    importSymbols.push("defineOpaqueType", "type OpaqueValueOf");
  }

  if (strategies.length > 0) {
    importSymbols.push("createGraphResolutionStrategy");
    if (strategies.includes("AddressableResourceIdentifier")) {
      importSymbols.push("type AddressableResourceIdentifier");
    }
    if (strategies.includes("stricterOnFailure")) {
      importSymbols.push("stricterOnFailure");
    }
  }

  if (projections.length > 0) {
    importSymbols.push("type ContentMap");
    if (!importSymbols.includes("type AddressableResourceIdentifier")) {
      importSymbols.push("type AddressableResourceIdentifier");
    }
    if (analysis.queries.some((query) => query.hasRedirects)) {
      importSymbols.push("type ResourceKey");
    }
    if (analysis.queries.some((query) => query.needsFailureProjection)) {
      if (!importSymbols.includes("type ResourceKey")) {
        importSymbols.push("type ResourceKey");
      }
      if (
        !importSymbols.includes("type ResolutionError") &&
        !importSymbols.includes("ResolutionError")
      ) {
        importSymbols.push("type ResolutionError");
      }
      importSymbols.push("toResolutionErrorData");
    }
    if (analysis.queries.some((query) => query.usesSetError)) {
      importSymbols.push("type ResolutionErrorData");
    }
  }

  if (datasourceTypes.length > 0) {
    for (const symbol of ["defineDataSourceFor", "type DataSource", "type ResourceLoadContext"]) {
      if (!importSymbols.includes(symbol)) {
        importSymbols.push(symbol);
      }
    }
    if (datasourcesNeedSourceRouteContext(program)) {
      if (!importSymbols.includes("type SourceRouteContext")) {
        importSymbols.push("type SourceRouteContext");
      }
    }
  }

  if (resolves.length > 0) {
    for (const symbol of [
      "createResourceGraphResolver",
      "type DataSource",
      "type IslandDependencyMap",
      "type IslandMap",
      "type ResolutionError",
      "type ResolutionBudgetOptions",
      "type ResolutionObserver",
      "type ResourceKey",
      "type SchedulingMode",
    ]) {
      if (symbol === "type ResolutionError" && importSymbols.includes("ResolutionError")) {
        continue;
      }
      if (!importSymbols.includes(symbol)) {
        importSymbols.push(symbol);
      }
    }
  }

  const parts: string[] = [GENERATED_MODULE_HEADER];

  if (importSymbols.length > 0) {
    parts.push(emitRuntimeImport(importFrom, importSymbols));
  }

  parts.push(...bodyParts);

  return { code: `${parts.join("\n\n")}\n` };
}
