/**
 * Merge resource + datasource + strategy + projection + resolve façade codegen
 * into one TypeScript module for the product path (`buildResources` / CLI).
 * Keeps `generateResources` / `generateStrategies` / `generateProjections` /
 * `generateDataSources` as focused unit-test entry points with separate imports.
 */
import type { Program } from "../../ir";
import { datasourcesNeedSourceRouteContext, emitDataSources } from "./datasources";
import type { GenerateResourcesOptions } from "./generators/generate-resources";
import { emitProjectionTypes, emitProjections } from "./projections";
import { emitPayloadTypes, emitRegistry, emitResources, emitScalars } from "./resources";
import { emitResolves } from "./resolve-facades";
import { emitStrategies } from "./strategies";
import { queryNeedsFailureProjection, queryUsesSetError } from "../../check/projection-graph";

const GENERATED_HEADER = "/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */";

const DEFAULT_IMPORT_FROM = "@xndrjs/ziel";
const DEFAULT_REGISTRY_TYPE_NAME = "ContentRegistry";

export type ComposeGeneratedModuleOptions = GenerateResourcesOptions & {
  /**
   * Optional property name stamped with the resource name on projection shells
   * and types (e.g. `"$type"` or `"__resource"`). Default: unset (no stamp).
   */
  resourceTag?: string;
};

export type ComposeGeneratedModuleResult = {
  /** Full TypeScript module source. */
  code: string;
};

type ResolvedOptions = {
  importFrom: string;
  registryTypeName: string;
  resourceTag: string | undefined;
};

function resolveOptions(options?: ComposeGeneratedModuleOptions): ResolvedOptions {
  return {
    importFrom: options?.importFrom ?? DEFAULT_IMPORT_FROM,
    registryTypeName: options?.registryTypeName ?? DEFAULT_REGISTRY_TYPE_NAME,
    resourceTag: options?.resourceTag,
  };
}

function emitRuntimeImport(importFrom: string, symbols: string[]): string {
  return `import { ${symbols.join(", ")} } from ${JSON.stringify(importFrom)};`;
}

/**
 * Compose a single generated module: scalars / ARIs / payloads / registry,
 * plus `createDataSources` when datasources are declared, and open strategy
 * builders, projectors, and resolve façades when the program has queries.
 *
 * Uses one header and one runtime import (`ari`, `s`,
 * `createGraphResolutionStrategy`, `defineDataSourceFor`,
 * `createResourceGraphResolver`, and related types as needed).
 */
export function composeGeneratedModule(
  program: Program,
  options?: ComposeGeneratedModuleOptions
): ComposeGeneratedModuleResult {
  const { importFrom, registryTypeName, resourceTag } = resolveOptions(options);

  const bodyParts: string[] = [];

  const scalars = emitScalars(program);
  if (scalars.length > 0) {
    bodyParts.push(scalars);
  }

  const resources = emitResources(program);
  if (resources.length > 0) {
    bodyParts.push(resources);
  }

  const payloadTypes = emitPayloadTypes(program);
  if (payloadTypes.length > 0) {
    bodyParts.push(payloadTypes);
  }

  const registry = emitRegistry(program, registryTypeName);
  if (registry.length > 0) {
    bodyParts.push(registry);
  }

  const datasources = emitDataSources(program, registryTypeName);
  if (datasources.length > 0) {
    bodyParts.push(datasources);
  }

  const strategies = emitStrategies(program, registryTypeName);
  if (strategies.length > 0) {
    bodyParts.push(strategies);
  }

  const projectionTypes = emitProjectionTypes(program, resourceTag);
  if (projectionTypes.length > 0) {
    bodyParts.push(projectionTypes);
  }

  const projections = emitProjections(program, registryTypeName, resourceTag);
  if (projections.length > 0) {
    bodyParts.push(projections);
  }

  const resolves = emitResolves(program, registryTypeName);
  if (resolves.length > 0) {
    bodyParts.push(resolves);
  }

  const importSymbols: string[] = [];
  if (resources.length > 0) {
    importSymbols.push("ari", "s");
  }

  if (strategies.length > 0) {
    importSymbols.push("createGraphResolutionStrategy");
  }

  if (projections.length > 0) {
    importSymbols.push("type ContentMap");
    if (program.queries.some((q) => q.projections.some((p) => p.resolveArms !== null))) {
      importSymbols.push("type ApplicationResourceIdentifier", "type ResourceKey");
    }
    if (program.queries.some((q) => queryNeedsFailureProjection(q))) {
      if (!importSymbols.includes("type ResourceKey")) {
        importSymbols.push("type ResourceKey");
      }
      if (
        !importSymbols.includes("type ResolutionError") &&
        !importSymbols.includes("ResolutionError")
      ) {
        importSymbols.push("type ResolutionError");
      }
    }
    if (program.queries.some((q) => queryUsesSetError(q))) {
      // Value import so consumers can `instanceof ResolutionError` from generated types.
      const typeIdx = importSymbols.indexOf("type ResolutionError");
      if (typeIdx >= 0) {
        importSymbols[typeIdx] = "ResolutionError";
      } else if (!importSymbols.includes("ResolutionError")) {
        importSymbols.push("ResolutionError");
      }
    }
  }

  if (datasources.length > 0) {
    for (const symbol of ["defineDataSourceFor", "type DataSource", "type ResourceLoadContext"]) {
      if (!importSymbols.includes(symbol)) {
        importSymbols.push(symbol);
      }
    }
    if (datasourcesNeedSourceRouteContext(program)) {
      if (!importSymbols.includes("type SourceRouteContext")) {
        importSymbols.push("type SourceRouteContext");
      }
    }
  }

  if (resolves.length > 0) {
    for (const symbol of [
      "createResourceGraphResolver",
      "type DataSource",
      "type IslandDependencyMap",
      "type IslandMap",
      "type ResolutionError",
      "type ResolutionBudgetOptions",
      "type ResolutionObserver",
      "type ResourceKey",
      "type SchedulingMode",
    ]) {
      if (symbol === "type ResolutionError" && importSymbols.includes("ResolutionError")) {
        continue;
      }
      if (!importSymbols.includes(symbol)) {
        importSymbols.push(symbol);
      }
    }
  }

  const parts: string[] = [GENERATED_HEADER];

  if (importSymbols.length > 0) {
    parts.push(emitRuntimeImport(importFrom, importSymbols));
  }

  parts.push(...bodyParts);

  return { code: `${parts.join("\n\n")}\n` };
}
