/**
 * Merge resource + datasource + strategy + projection + resolve façade codegen
 * into one TypeScript module for the product path (`buildGeneratedModule` / CLI).
 * Keeps `generateResources` / `generateStrategies` / `generateProjections` /
 * `generateDataSources` as focused unit-test entry points with separate imports.
 */
import type { ProgramAnalysis } from "../../check";
import type { Program } from "../../ir";
import {
  datasourcesNeedSourceRouteContext,
  emitDataSourceTypes,
  emitQueryDataSourceFactories,
} from "./datasources";
import type { GenerateResourcesOptions } from "./generators/generate-resources";
import { emitProjectionTypes, emitProjections } from "./projections";
import { emitPayloadTypes, emitRegistry, emitResources, emitScalars } from "./resources";
import { emitResolves } from "./resolve-facades";
import { emitStrategies } from "./strategies";
import { codegenAnalysis } from "./analysis";

const GENERATED_HEADER = "/* Generated by @xndrjs/ziel/compile. Do not edit by hand. */";

const DEFAULT_IMPORT_FROM = "@xndrjs/ziel";
const DEFAULT_REGISTRY_TYPE_NAME = "ContentRegistry";

export type ComposeGeneratedModuleOptions = GenerateResourcesOptions & {
  /**
   * Optional property name stamped with the resource name on projection shells
   * and types (e.g. `"$type"` or `"__resource"`). Default: unset (no stamp).
   */
  resourceTag?: string;
};

export type ComposeGeneratedModuleResult = {
  /** Full TypeScript module source. */
  code: string;
};

type ResolvedOptions = {
  importFrom: string;
  registryTypeName: string;
  resourceTag: string | undefined;
};

function resolveOptions(options?: ComposeGeneratedModuleOptions): ResolvedOptions {
  return {
    importFrom: options?.importFrom ?? DEFAULT_IMPORT_FROM,
    registryTypeName: options?.registryTypeName ?? DEFAULT_REGISTRY_TYPE_NAME,
    resourceTag: options?.resourceTag,
  };
}

function emitRuntimeImport(importFrom: string, symbols: string[]): string {
  return `import { ${symbols.join(", ")} } from ${JSON.stringify(importFrom)};`;
}

/**
 * Compose a single generated module: scalars / ARIs / payloads / registry,
 * plus per-query `create*DataSources` when datasources are declared, and open
 * strategy builders, projectors, and resolve façades when the program has queries.
 *
 * Uses one header and one runtime import (`ari`, `s`,
 * `createGraphResolutionStrategy`, `defineDataSourceFor`,
 * `createResourceGraphResolver`, and related types as needed).
 */
export function composeGeneratedModule(
  input: Program | ProgramAnalysis,
  options?: ComposeGeneratedModuleOptions
): ComposeGeneratedModuleResult {
  const analysis = codegenAnalysis(input);
  const program = analysis.program;
  const { importFrom, registryTypeName, resourceTag } = resolveOptions(options);

  const bodyParts: string[] = [];

  const scalars = emitScalars(program);
  if (scalars.length > 0) {
    bodyParts.push(scalars);
  }

  const resources = emitResources(program);
  if (resources.length > 0) {
    bodyParts.push(resources);
  }

  const payloadTypes = emitPayloadTypes(program);
  if (payloadTypes.length > 0) {
    bodyParts.push(payloadTypes);
  }

  const registry = emitRegistry(program, registryTypeName);
  if (registry.length > 0) {
    bodyParts.push(registry);
  }

  const datasourceTypes = emitDataSourceTypes(program);
  if (datasourceTypes.length > 0) {
    bodyParts.push(datasourceTypes);
  }

  const strategies = emitStrategies(analysis, registryTypeName);
  if (strategies.length > 0) {
    bodyParts.push(strategies);
  }

  // After strategies so `{Query}ExecutionContext` aliases exist for factory return types.
  const queryDataSources = emitQueryDataSourceFactories(program, registryTypeName);
  if (queryDataSources.length > 0) {
    bodyParts.push(queryDataSources);
  }

  const projectionTypes = emitProjectionTypes(analysis, resourceTag);
  if (projectionTypes.length > 0) {
    bodyParts.push(projectionTypes);
  }

  const projections = emitProjections(analysis, registryTypeName, resourceTag);
  if (projections.length > 0) {
    bodyParts.push(projections);
  }

  const resolves = emitResolves(analysis, registryTypeName);
  if (resolves.length > 0) {
    bodyParts.push(resolves);
  }

  const importSymbols: string[] = [];
  if (resources.length > 0) {
    importSymbols.push("ari", "s");
  }

  if (strategies.length > 0) {
    importSymbols.push("createGraphResolutionStrategy");
    if (strategies.includes("AddressableResourceIdentifier")) {
      importSymbols.push("type AddressableResourceIdentifier");
    }
    if (strategies.includes("stricterOnFailure")) {
      importSymbols.push("stricterOnFailure");
    }
  }

  if (projections.length > 0) {
    importSymbols.push("type ContentMap");
    if (!importSymbols.includes("type AddressableResourceIdentifier")) {
      importSymbols.push("type AddressableResourceIdentifier");
    }
    if (analysis.queries.some((query) => query.hasRedirects)) {
      importSymbols.push("type ResourceKey");
    }
    if (analysis.queries.some((query) => query.needsFailureProjection)) {
      if (!importSymbols.includes("type ResourceKey")) {
        importSymbols.push("type ResourceKey");
      }
      if (
        !importSymbols.includes("type ResolutionError") &&
        !importSymbols.includes("ResolutionError")
      ) {
        importSymbols.push("type ResolutionError");
      }
      importSymbols.push("toResolutionErrorData");
    }
    if (analysis.queries.some((query) => query.usesSetError)) {
      importSymbols.push("type ResolutionErrorData");
    }
  }

  if (datasourceTypes.length > 0) {
    for (const symbol of ["defineDataSourceFor", "type DataSource", "type ResourceLoadContext"]) {
      if (!importSymbols.includes(symbol)) {
        importSymbols.push(symbol);
      }
    }
    if (datasourcesNeedSourceRouteContext(program)) {
      if (!importSymbols.includes("type SourceRouteContext")) {
        importSymbols.push("type SourceRouteContext");
      }
    }
  }

  if (resolves.length > 0) {
    for (const symbol of [
      "createResourceGraphResolver",
      "type DataSource",
      "type IslandDependencyMap",
      "type IslandMap",
      "type ResolutionError",
      "type ResolutionBudgetOptions",
      "type ResolutionObserver",
      "type ResourceKey",
      "type SchedulingMode",
    ]) {
      if (symbol === "type ResolutionError" && importSymbols.includes("ResolutionError")) {
        continue;
      }
      if (!importSymbols.includes(symbol)) {
        importSymbols.push(symbol);
      }
    }
  }

  const parts: string[] = [GENERATED_HEADER];

  if (importSymbols.length > 0) {
    parts.push(emitRuntimeImport(importFrom, importSymbols));
  }

  parts.push(...bodyParts);

  return { code: `${parts.join("\n\n")}\n` };
}
