/**
 * @generated by @xndrjs/contentful-to-zod
 * Do not edit manually.
 */

import { z } from "zod";

/** @generated from space locales snapshot */
export const CONTENTFUL_LOCALE_CODES = ["en-US", "it-IT"] as const;
export type ContentfulLocaleCode = (typeof CONTENTFUL_LOCALE_CODES)[number];
export const ContentfulLocaleCodeSchema = z.enum(CONTENTFUL_LOCALE_CODES);
export const CONTENTFUL_DEFAULT_LOCALE = "en-US" as const;

/**
 * Flat/CMA field wrapper: omitted keys and explicit null both normalize to `null`.
 * Use after `flatten*` or when parsing a normalized flat shape.
 */
export function flatField<T extends z.ZodType>(schema: T) {
  return schema
    .nullable()
    .optional()
    .transform((value) => value ?? null);
}

/**
 * Delivery/Preview field wrapper: omitted keys and explicit null both normalize to `null`.
 * CMA `required` does not apply at the transport boundary.
 */
export function transportField<T extends z.ZodType>(schema: T) {
  return schema
    .nullable()
    .optional()
    .transform((value) => value ?? null);
}

export const ContentfulResourceLinkSchema = z.object({
  sys: z.object({
    type: z.literal("Link"),
    linkType: z.string(),
    id: z.string(),
  }),
});

/** Loose Delivery/Preview entry metadata; extra Contentful fields pass through. */
export const ContentfulEntrySysSchema = z.looseObject({
  id: z.string(),
  type: z.literal("Entry"),
  createdAt: z.string(),
  updatedAt: z.string(),
  revision: z.number(),
  contentType: z.object({
    sys: z.object({
      type: z.literal("Link"),
      linkType: z.literal("ContentType"),
      id: z.string(),
    }),
  }),
  space: ContentfulResourceLinkSchema,
  environment: ContentfulResourceLinkSchema,
  locale: ContentfulLocaleCodeSchema.optional(),
  publishedVersion: z.number().optional(),
});

export type ContentfulResourceLink = z.infer<typeof ContentfulResourceLinkSchema>;
export type ContentfulEntrySys = z.infer<typeof ContentfulEntrySysSchema>;

/** Structural Delivery/Preview entry envelope (any content type); fields are untyped. */
export const ContentfulEntryEnvelopeSchema = z.object({
  sys: ContentfulEntrySysSchema,
  fields: z.record(z.string(), z.unknown()),
});

export type ContentfulEntryEnvelope = z.infer<typeof ContentfulEntryEnvelopeSchema>;

/** Loose Delivery/Preview asset metadata; extra Contentful fields pass through. */
export const ContentfulAssetSysSchema = z.looseObject({
  id: z.string(),
  type: z.literal("Asset"),
  createdAt: z.string(),
  updatedAt: z.string(),
  revision: z.number(),
  space: ContentfulResourceLinkSchema,
  environment: ContentfulResourceLinkSchema,
  locale: ContentfulLocaleCodeSchema.optional(),
  publishedVersion: z.number().optional(),
});

export type ContentfulAssetSys = z.infer<typeof ContentfulAssetSysSchema>;

export const ContentfulAssetFieldsSchema = z.object({
  title: transportField(z.string()),
  file: transportField(
    z.object({
      url: z.string(),
      fileName: z.string().optional(),
      contentType: z.string().optional(),
    })
  ),
});

export type ContentfulAssetFields = z.infer<typeof ContentfulAssetFieldsSchema>;

/** Resolved Delivery/Preview asset payload. */
export const ContentfulAssetSchema = z.object({
  sys: ContentfulAssetSysSchema,
  fields: ContentfulAssetFieldsSchema,
});

export type ContentfulAsset = z.infer<typeof ContentfulAssetSchema>;

export const ContentfulLocationSchema = z.object({ lat: z.number(), lon: z.number() });
export type ContentfulLocation = z.infer<typeof ContentfulLocationSchema>;

export const ContentfulEntryLinkSchema = z.object({
  sys: z.object({ type: z.literal("Link"), linkType: z.literal("Entry"), id: z.string() }),
});
export type ContentfulEntryLink = z.infer<typeof ContentfulEntryLinkSchema>;

export const ContentfulAssetLinkSchema = z.object({
  sys: z.object({ type: z.literal("Link"), linkType: z.literal("Asset"), id: z.string() }),
});
export type ContentfulAssetLink = z.infer<typeof ContentfulAssetLinkSchema>;

export const AuthorFieldsSchema = z.object({
  name: flatField(z.string()),
});

export type AuthorFields = z.infer<typeof AuthorFieldsSchema>;

export const AuthorLocalizedFieldsSchema = z.object({
  name: transportField(z.string()),
});

export type AuthorLocalizedFields = z.infer<typeof AuthorLocalizedFieldsSchema>;

export const AuthorLocalizedEntrySchema = z.object({
  sys: ContentfulEntrySysSchema.extend({
    contentType: z.object({
      sys: z.object({
        type: z.literal("Link"),
        linkType: z.literal("ContentType"),
        id: z.literal("author"),
      }),
    }),
  }),
  fields: AuthorLocalizedFieldsSchema,
});

export type AuthorLocalizedEntry = z.infer<typeof AuthorLocalizedEntrySchema>;

export const BlogPostFieldsSchema = z.object({
  title: flatField(z.string().max(256)),
  slug: flatField(z.string()),
  author: flatField(
    z.object({
      sys: z.object({ type: z.literal("Link"), linkType: z.literal("Entry"), id: z.string() }),
    })
  ),
  excerpt: flatField(z.string()),
  metadata: flatField(z.object({ seoTitle: z.string(), noIndex: z.boolean().optional() })),
});

export type BlogPostFields = z.infer<typeof BlogPostFieldsSchema>;

export const BlogPostLocalizedFieldsSchema = z.object({
  title: transportField(z.record(ContentfulLocaleCodeSchema, z.string().max(256))),
  slug: transportField(z.string()),
  author: transportField(
    z.object({
      sys: z.object({ type: z.literal("Link"), linkType: z.literal("Entry"), id: z.string() }),
    })
  ),
  excerpt: transportField(z.record(ContentfulLocaleCodeSchema, z.string())),
  metadata: transportField(
    z.record(
      ContentfulLocaleCodeSchema,
      z.object({ seoTitle: z.string(), noIndex: z.boolean().optional() })
    )
  ),
});

export type BlogPostLocalizedFields = z.infer<typeof BlogPostLocalizedFieldsSchema>;

export const BlogPostLocalizedEntrySchema = z.object({
  sys: ContentfulEntrySysSchema.extend({
    contentType: z.object({
      sys: z.object({
        type: z.literal("Link"),
        linkType: z.literal("ContentType"),
        id: z.literal("blogPost"),
      }),
    }),
  }),
  fields: BlogPostLocalizedFieldsSchema,
});

export type BlogPostLocalizedEntry = z.infer<typeof BlogPostLocalizedEntrySchema>;

/** @generated from content type snapshot */
export const CONTENTFUL_CONTENT_TYPE_IDS = ["author", "blogPost"] as const;
export type ContentfulContentTypeId = (typeof CONTENTFUL_CONTENT_TYPE_IDS)[number];
export const ContentfulContentTypeIdSchema = z.enum(CONTENTFUL_CONTENT_TYPE_IDS);

/** Localized-only entry type per content type id. */
export type ContentfulLocalizedEntryByContentType = {
  author: AuthorLocalizedEntry;
  blogPost: BlogPostLocalizedEntry;
};

/** Zod localized entry schema per content type id (for typed parse + dispatch). */
export const ContentfulLocalizedEntrySchemaByContentType = {
  author: AuthorLocalizedEntrySchema,
  blogPost: BlogPostLocalizedEntrySchema,
} as const satisfies {
  [K in ContentfulContentTypeId]: z.ZodType<ContentfulLocalizedEntryByContentType[K]>;
};

/** Localized-only entry (any content type in this snapshot). */
export const ContentfulResolvedLocalizedEntrySchema = z.union([
  AuthorLocalizedEntrySchema,
  BlogPostLocalizedEntrySchema,
]);
export type ContentfulResolvedLocalizedEntry = z.infer<
  typeof ContentfulResolvedLocalizedEntrySchema
>;

/** Read one locale from a localized field map; missing locale or null input → `null`. */
export function pickLocale<T>(
  value: Record<ContentfulLocaleCode, T> | null,
  locale: ContentfulLocaleCode = CONTENTFUL_DEFAULT_LOCALE
): T | null {
  if (value === null) {
    return null;
  }
  return value[locale] ?? null;
}

/** Flatten validated `AuthorLocalizedFields` (from `entry.fields`) to `AuthorFields` for a single locale. */
export function flattenAuthorLocalizedFields(
  fields: AuthorLocalizedFields,
  _locale: ContentfulLocaleCode = CONTENTFUL_DEFAULT_LOCALE
): AuthorFields {
  return {
    name: fields.name ?? null,
  };
}

/** Flatten validated `BlogPostLocalizedFields` (from `entry.fields`) to `BlogPostFields` for a single locale. */
export function flattenBlogPostLocalizedFields(
  fields: BlogPostLocalizedFields,
  _locale: ContentfulLocaleCode = CONTENTFUL_DEFAULT_LOCALE
): BlogPostFields {
  return {
    title: pickLocale(fields.title ?? null, _locale),
    slug: fields.slug ?? null,
    author: fields.author ?? null,
    excerpt: pickLocale(fields.excerpt ?? null, _locale),
    metadata: pickLocale(fields.metadata ?? null, _locale),
  };
}

/** Error when a resolved entry's content type is not allowed for a link field (from CMA `linkContentType`). */
export class LinkFieldTargetError extends Error {
  constructor(
    public readonly parentContentTypeId: string,
    public readonly fieldId: string,
    public readonly resolvedContentTypeId: string,
    public readonly allowedContentTypeIds: readonly string[]
  ) {
    super(
      `Entry sys.contentType.sys.id is "${resolvedContentTypeId}" but link field "${parentContentTypeId}.${fieldId}" only allows: ${allowedContentTypeIds.join(", ")}`
    );
    this.name = "LinkFieldTargetError";
  }
}

function readResolvedEntryContentTypeId(entry: unknown): string {
  if (typeof entry !== "object" || entry === null) {
    throw new Error("Expected a resolved Contentful entry object");
  }
  const sys = (entry as { sys?: unknown }).sys;
  if (typeof sys !== "object" || sys === null) {
    throw new Error("Resolved entry is missing sys");
  }
  const contentType = (sys as { contentType?: unknown }).contentType;
  if (typeof contentType !== "object" || contentType === null) {
    throw new Error("Resolved entry sys is missing contentType");
  }
  const contentTypeSys = (contentType as { sys?: unknown }).sys;
  if (typeof contentTypeSys !== "object" || contentTypeSys === null) {
    throw new Error("Resolved entry sys.contentType is missing sys");
  }
  const id = (contentTypeSys as { id?: unknown }).id;
  if (typeof id !== "string" || id.length === 0) {
    throw new Error("Resolved entry sys.contentType.sys.id is not a string");
  }
  return id;
}

export interface ResolvedEntryForLinkFieldMap {
  blogPost: {
    author: AuthorLocalizedEntry;
  };
}

export interface LinkFieldHandlersMap {
  blogPost: {
    author: (entry: unknown) => AuthorLocalizedEntry;
  };
}

export type LinkParentContentTypeId = keyof ResolvedEntryForLinkFieldMap;

export type LinkFieldName<CType extends LinkParentContentTypeId> =
  keyof ResolvedEntryForLinkFieldMap[CType] & string;

export type ResolvedEntryForLinkField<
  CType extends LinkParentContentTypeId,
  Field extends LinkFieldName<CType>,
> = ResolvedEntryForLinkFieldMap[CType][Field];

export interface LinkFieldAllowedContentTypesMap {
  blogPost: {
    author: readonly ["author"];
  };
}

export type LinkFieldAllowedContentTypes<
  CType extends LinkParentContentTypeId,
  Field extends LinkFieldName<CType> & keyof LinkFieldAllowedContentTypesMap[CType],
> = LinkFieldAllowedContentTypesMap[CType][Field];

/** Allowed resolved entry content type ids per link field (`linkContentType` from CMA). */
export const LINK_FIELD_ALLOWED_CONTENT_TYPES = {
  blogPost: {
    author: ["author"] as const,
  },
} as const;

const LINK_FIELD_HANDLERS = {
  blogPost: {
    author: (entry: unknown) => {
      const parentContentTypeId = "blogPost";
      const fieldId = "author";
      const allowed = LINK_FIELD_ALLOWED_CONTENT_TYPES[parentContentTypeId][fieldId];
      const resolvedId = readResolvedEntryContentTypeId(entry);
      switch (resolvedId) {
        case "author":
          return AuthorLocalizedEntrySchema.parse(entry);
        default:
          throw new LinkFieldTargetError(parentContentTypeId, fieldId, resolvedId, allowed);
      }
    },
  },
} as const;

/**
 * Allowed resolved entry content type ids for a parent link field (`linkContentType` from CMA).
 */
export function getAllowedEntryLinkContentTypes<
  const CType extends LinkParentContentTypeId,
  const Field extends LinkFieldName<CType> & keyof LinkFieldAllowedContentTypesMap[CType],
>(ctype: CType, fieldName: Field): LinkFieldAllowedContentTypes<CType, Field> {
  return (LINK_FIELD_ALLOWED_CONTENT_TYPES[ctype] as LinkFieldAllowedContentTypesMap[CType])[
    fieldName
  ];
}

/**
 * Parse a resolved entry (include/fetch) for a parent link field, using CMA `linkContentType` rules.
 * Return type is a single entry type or a union when the field allows multiple targets.
 */
export function parseEntryAsLinkField<
  const CType extends LinkParentContentTypeId,
  const Field extends LinkFieldName<CType>,
>(ctype: CType, fieldName: Field, entry: unknown): ResolvedEntryForLinkField<CType, Field> {
  return (
    LINK_FIELD_HANDLERS[ctype] as {
      [F in LinkFieldName<CType>]: (entry: unknown) => ResolvedEntryForLinkField<CType, F>;
    }
  )[fieldName](entry);
}

export type LinkFieldDescriptor = {
  fieldId: string;
  linkType: "Entry" | "Asset";
  cardinality: "one" | "many";
};

/**
 * Entry/Asset link fields per content type (from CMA).
 * Order follows the content model field order.
 */
export const LINK_FIELDS_BY_CONTENT_TYPE = {
  author: [],
  blogPost: [
    {
      fieldId: "author",
      linkType: "Entry",
      cardinality: "one",
    },
  ],
} as const satisfies Record<ContentfulContentTypeId, readonly LinkFieldDescriptor[]>;
