export * from "./asset.shape.js";
export * from "./footer.shape.js";
export * from "./hero.shape.js";
export * from "./menu.shape.js";
export * from "./page.shape.js";
export * from "./price.shape.js";
export * from "./product.shape.js";
export * from "./tab.shape.js";
export * from "./tabs.shape.js";
